project:
  type: book
  output-dir: docs

book:
  title: "Through the Looking Glass: I. Why Cross-Fertilize?"
  author: 
    name: Curtis M. Lively
    attributes:
      corresponding: True
    affiliations:
      - name: | 
                Indiana University Bloomington
                Department of Biology
        department: Biology
        address:  Biology Bldg. 117B
        city: Bloomington
        region: IN
        country: US
        postal-code: 47405
        url: https://biology.indiana.edu/index.html
    email: clively@indiana.edu
    url: https://biology.indiana.edu/about/faculty/lively-curt.html
  date: last-modified
  date-format: "YYYY"
  abstract: |
    The following pages represent the first volume of a book. The main goal is to introduce the evolutionary problem of sexual reproduction with a focus on competition between sexual and asexual females. But I also incorporate some ideas on genetic polymorphism and phenotypic plasticity with the goal of exploring "variation strategies" more generally. Finally, I try to weave in some history of the field along with some philosophy of science. 
  description: | 
    Book on the evolutionary problem of sexual reproduction
  references: references.bib
  cover-image: images/cover.png
  cover-image-alt: book cover with title, author, illustrator, and illustration of Red Queen chesspiece and two snails
  sharing: [twitter, facebook, linkedin]
  downloads: [pdf, epub, docx]
  sidebar:
    style: "docked"
    logo: images/cover.png
    search: true
    tools: 
      - icon: twitter-x
        href: https://twitter.com/curt_lively
        aria-label: Twitter
  doi: 10.5967/gbd3-ka07
  illustrator: Zoe Michelle Dinges
  keyword: evolution, coevolution, "host-parasite interactions", "Muller's ratchet", parthenogenesis, "Red Queen hypothesis", "sexual reproduction"
  language: en-US
  license: "CC BY"
  publisher: Indiana University Bloomington Libraries Publishing
  publisher-place: Bloomington, IN
  submitted: "01 June 2023"
  type: book
  volume: 1
  favicon: images/favicon.ico
  site-url: https://iulibscholcomm.github.io/through-the-looking-glass
  repo-url: https://github.com/IULibScholComm/through-the-looking-glass
  issue-url: https://github.com/IULibScholComm/through-the-looking-glass/issues/new
  pdf-url: https://iulibscholcomm.github.io/through-the-looking-glass/Through-the-Looking-Glass.pdf
  repo-actions: [source, issue]
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  open-graph: 
    image: images/cover-thumbnail.jpg
    image-alt: book cover with title, author, illustrator, and illustration of Red Queen chesspiece and two snails
  twitter-card:  
    card-style: summary
    creator: "@curt_lively"
    image: images/cover-thumbnail.jpg
    image-alt: book cover with title, author, illustrator, and illustration of Red Queen chesspiece and two snails


  chapters:
    - index.qmd
    - why-sex.qmd
    - eco-hyp.qmd
    - eco-hyp-cont.qmd
    - self-non.qmd
    - gyno-fish.qmd
    - rat-red.qmd
    - over-future.qmd
    - glossary.qmd
    - references.qmd

citation:
  type: book
  publisher: "Indiana University Bloomington Libraries Publishing"

google-scholar: true
csl: ecology-letters.csl
bibliography: references.bib
citations-hover: true

format:
  html:
    css: style.css
    html-math-method: mathjax
    theme: journal
    toc: true
    toc-title: Contents
    toc-expand: true
    anchor-sections: true
    number-sections: true
    smooth-scroll: true
    section-divs: true
    fig-cap-location: bottom
    tbl-cap-location: top
    link-external-newwindow: true
    copyright: Curtis M. Lively
    date-modified: last-modified
    license: "CC BY ND"
    citeproc: true
    html-q-tags: true
    footnotes-hover: true
    include-in-header: 
      - text: <meta name="google-site-verification" content="eJHds-HZowhP4fOmzTkps1RTCDKNi3ViSQ2BSaFVA7Y" />
    keywords: ["evolution", "coevolution", "host-parasite interactions", "Muller's ratchet", "parthenogenesis", "Red Queen hypothesis", "sexual reproduction"]

  titlepage-pdf:
    coverpage: true
    coverpage-bg-image: "images/cover.png"
    coverpage-theme:
      title-style: none
      author-style: none
      date-style: "none"
    titlepage: true
    titlepage-logo: "images/iublpub_logo.png"
    titlepage-geometry: ["top=3in", "bottom=1.5in", "right=1in", "left=1in"]
    titlepage-footer: | # text
      Indiana University Bloomington Libraries Publishing\
      Bloomington, Indiana
    titlepage-theme:
      elements: ["\\titleblock", "\\authorblock", "\\Large Illustrated by Zoe Michelle Dinges", "\\vfill", "\\logoblock", "\\footerblock"]
      title-style: "plain"
      footer-fontfamily: QTHelvetCnd.otf
      title-fontstyle: ["Huge", "textbf"]
      title-space-after: 1.5cm
      author-style: "plain"
      author-fontsize: 20
      affiliation-style: "none"
      logo-size: "0.5\\paperwidth"
      footer-fontsize: 15
    titlepage-include-file: tex/copyright.tex
    documentclass: book
    keep-tex: true
    toc: true
    toc-title: Contents
    lof: true
    lot: true
    number-sections: true
    linkcolor: blue
    papersize: letter
    indent: false
    reference-location: block
    cite-method: citeproc
    citeproc: true
    link-citations: true
    lang: en-US
    keywords: ["biology", "evolution", "sexual reproduction", "evolutionary biology"]
    subject: "evolutionary biology"
    latex-auto-mk: true
    latex-auto-install: True
    header-includes: |
      \widowpenalty=10000         % avoid widows
      \clubpenalty=10000          % avoid orphans
      \interfootnotelinepenalty=10000 % avoid footnote splitting across pages
      \usepackage[scale=3.5]{ccicons}

  epub:
    css: style.css
    html-math-method: mathml
    html-q-tags: true
    toc: true
    toc-title: Contents
    number-sections: true
    citeproc: true
    lang: en-US
    fig-responsive: true

  docx:
    toc: true
    toc-title: Contents
    citeproc: true
    lang: en-US
    reference-doc: custom-reference-doc.docx
    fig-align: center
    link-citations: true
    subject: evolution, coevolution, "host-parasite interactions", "Muller's ratchet", parthenogenesis, "Red Queen hypothesis", "sexual reproduction"

    