project:
  type: book
  output-dir: docs

book:
  title: "Through the Looking Glass: I. Why Cross-Fertilize?"
  author: 
    name: Curtis M. Lively
    attributes:
      corresponding: True
    affiliations:
      - name: | 
                Indiana University Bloomington
                Department of Biology
        department: Biology
        address:  Biology Bldg. 117B
        city: Bloomington
        region: IN
        country: US
        postal-code: 47405
        url: https://biology.indiana.edu/index.html
    email: clively@indiana.edu
    url: https://biology.indiana.edu/about/faculty/lively-curt.html
  date: last-modified
  date-format: "DD MMMM YYYY"
  references: references.bib
  cover-image-alt: book cover with title, author, and image of red queen chesspiece and two snails
  sharing: [twitter, facebook, linkedin]
  downloads: [pdf, epub, docx]
  sidebar:
    style: "floating"
    logo: images/cover.jpg
    search: true
    tools: 
      - icon: person-circle
        href: https://biology.indiana.edu/about/faculty/lively-curt.html
      - icon: twitter
        href: https://twitter.com/curt_lively
  doi: 10.5967/gbd3-ka07
  illustrator: Zoe Michelle Dinges
  keyword: biology, "sexual reproduction", evolution, "evolutionary biology"
  language: en-US
  license: "CC BY"
  publisher: Scholarly Communication Department, Indiana University Bloomington Libraries
  publisher-place: Bloomington, IN
  status: "advance publication"
  submitted: "01 June 2023"
  type: book
  favicon: images/favicon.ico
  site-url: https://iulibscholcomm.github.io/through-the-looking-glass
  repo-url: https://github.com/IULibScholComm/through-the-looking-glass
  issue-url: https://github.com/IULibScholComm/through-the-looking-glass/issues/new
  pdf-url: https://iulibscholcomm.github.io/through-the-looking-glass/Through-the-Looking-Glass.pdf
  repo-actions: [edit, issue, source]
  reader-mode: true
  # cookie-consent: "implied"
  page-navigation: true
  back-to-top-navigation: true
  image: images/cover.jpg
  open-graph: true
  twitter-card:  
    card-style: summary
    creator: "@curt_lively"

  chapters:
    - index.qmd
    - why-sex.qmd
    - eco-hyp.qmd
    - eco-hyp-cont.qmd
    - self-non.qmd
    - gyno-fish.qmd
    - rat-red.qmd
    - over-future.qmd
    - glossary.qmd
    - references.qmd

citation:
  type: book
  medium: digital
  author: Curtis Lively
  issued: 2023
  title: "Through the Looking Glass: Coevolution, Polymorphism, and Sexual Reproduction"
  publisher-place: Bloomington, Indiana, US
  publisher: Indiana University Libraries Publishing

google-scholar: true

csl: ecology-letters.csl
bibliography: references.bib

format:
  html:
    css: style.css
    html-math-method: mathjax
    cover-image: images/cover.jpg
    theme: journal
    toc: true
    toc-title: Contents
    toc-expand: true
    anchor-sections: true
    number-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    copyright: Curtis M. Lively
    date-modified: last-modified
    license: "CC BY"
    code-fold: true
    code-tools: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-overflow: scroll
    highlight-style: a11y
    code-copy: hover
    code-link: false
    warning: false
    prompt: false
    output: true
    html-q-tags: true
    footnotes-hover: true
    include-in-header: 
      - text: <meta name="google-site-verification" content="eJHds-HZowhP4fOmzTkps1RTCDKNi3ViSQ2BSaFVA7Y" />

  titlepage-pdf:
    coverpage: true
    coverpage-bg-image: "images/cover.png"
    coverpage-theme:
      title-style: none
      author-style: none
      date-style: "none"
    titlepage: true
    titlepage-logo: "images/iublpub_logo.png"
    titlepage-geometry: ["top=3in", "bottom=1.5in", "right=1in", "left=1in"]
    titlepage-footer: | # text
      Indiana University Bloomington Libraries Publishing\
      Bloomington, Indiana
    titlepage-theme:
      elements: ["\\titleblock", "\\authorblock", "\\Large Illustrated by Zoe Michelle Dinges", "\\vfill", "\\logoblock", "\\footerblock"]
      title-style: "plain"
      footer-fontfamily: QTHelvetCnd.otf
      title-fontstyle: ["Huge", "textbf"]
      title-space-after: 1.5cm
      author-style: "plain"
      author-fontsize: 20
      affiliation-style: "none"
      logo-size: "0.5\\paperwidth"
      footer-fontsize: 15
    documentclass: book
    keep-tex: true
    toc: true
    toc-title: Contents
    lof: true
    lot: true
    number-sections: true
    linkcolor: blue
    papersize: letter
    reference-location: block
    cite-method: citeproc
    lang: en-US
    echo: false
    warning: false
    error: false
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: a11y
    output: true
    header-includes: |
      \widowpenalty=10000         % avoid widows
      \clubpenalty=10000          % avoid orphans
      \interfootnotelinepenalty=10000 % avoid footnote splitting across pages
      \usepackage[scale=3.5]{ccicons}
  epub:
    epub-cover-image: images/cover.png
    css: style.css
    html-q-tags: true
    toc: true
    toc-title: Contents
    number-sections: true
    citeproc: true
    lang: en-US
    fig-responsive: true
    code-fold: true
    code-overflow: scroll
    code-line-numbers: true
    code-copy: hover
    highlight-style: a11y
    warning: false
    error: false
    output: true
  docx:
    toc: true
    toc-title: Contents
    citeproc: true
    lang: en-US
    citation: true
    reference-doc: custom-reference-doc.docx
    highlight-style: a11y
    echo: false
    warning: false
    error: false
    output: true
    fig-align: center
    link-citations: true
