---
title: "Sim for fig 1.2"
author: "Curt Lively"
date: '2023-06-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages to make the plot, warning=FALSE}
library(plotly)
library(ggthemes)
library(dplyr)
```

```{r test}
a = 0.0001  #a is a constant that gives the sensitivity to total population density
d = 1.0 # d is the death rate.  Here I set d=1, meaning an annual species.
b = 3.0 # b is the number of offspring prouduced by a single female (sexual or asexual)
c = 0  # c is a constant that gives the sensitivity of the death rate to density.  Here set = 0.
#s = 1/2 # s is the frequency of males in the sexual subpopulation.  (1-s) gives the freq of females in sexual popl
#f is freq of females

Fig12 <- data.frame("f" = 0, "Generation" = 0, "Asexuals" = 0, "Sexuals" = 0)

for(f in c(0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8)){
# anayltical solutions: carrying capacities for sexual and asexuals are set by the parameters given above,
# following Lively (2009) J Evol Biol. doi: 10.1111/j.1420-9101.2009.01824.x
Ksex = (f*b - d)/((f)*a + c) #solution for carrying capacity of sexual population
Kasex = (b - d)/(a + c) #solution for carrying capacity of asexual population

# intitial conditions.  Sex initiated at Ksex.  Asex at 0.
Sex = Ksex 
Asex = 0

Gasex = 100 #generation at which a single asexual female is introduced

T = 200 # T is the number of time steps in addition to time step 0
time = c(1:T)  #sets up do loop for i = 1 to T

outSex = vector()  # outSex vector
outSex[1]=Sex[1]

outAsex = vector()  # outAsex  vector
outAsex[1]=Asex[1]

for(i in 1:T)

{
  outSex[i] = Sex[i]
  Sex[i+1] = Sex[i] - Sex[i]*(d + c*(Sex[i]+Asex[i])) + Sex[i]*(f)*(b - a*(Sex[i]+Asex[i]))
  
  if(i == Gasex)
    {
    Asex[i] = Asex[i] + 1
    }
  
  outAsex[i] = Asex[i]
  Asex[i+1] = Asex[i] - Asex[i]*d + Asex[i]*(b - a*(Sex[i]+Asex[i]))
Fig12 <- add_row(Fig12, "f" = f, "Generation" = i, "Asexuals" = Asex[i], "Sexuals" = Sex[i])
}}

Fig12 <- filter(Fig12, Generation > 0)
library(tidyr)
#Fig12 <- pivot_longer(Fig12, cols = Asexuals:Sexuals, names_to = "Mode", values_to = "Number")
Fig12$visible = rep(FALSE, length(Fig12$Generation))
```


```{r}
curtstheme <- theme_tufte() + theme(
  axis.title.x = element_text(size=14,face="bold", vjust = -1),
  axis.title.y = element_text(size=14,face="bold", vjust = -1), 
  axis.text.x = element_text(face="bold", size=14), 
  axis.text.y = element_text(face="bold", size=14), 
  plot.title = element_text(face = "bold", size = 24, hjust = 0.5),
  plot.subtitle= element_text(size = 14, hjust = 0.5),
  plot.caption = element_text(size = 12, hjust = 0.5),
  axis.line = element_line(size = 1),
  axis.ticks = element_line(size = 1),
  axis.ticks.length = unit(0.25, "cm"))

points <- ggplot(Fig12) + geom_point(aes(x = Generation, y = Sexuals, frame = f), color = "#FF4242") + geom_point(aes(x = Generation, y = Asexuals, frame = f), color = "#235FA4") +
  scale_x_continuous(name="GENERATION") + 
  scale_y_continuous(name="NUMBER\n", limits = c(0, 21500)) +
  scale_color_manual(values = c(Asexuals = "#235FA4", Sexuals = "#FF4242"))  +
  annotate(geom = "text", x= 25, y = 1000, label = "Asexuals", color = "#235FA4", size = 6) +
  annotate(geom = "text", x= 190, y = 1000, label = "Sexuals", color = "#FF4242", size = 6) +
  theme(aspect.ratio = 1/1.5) + curtstheme +  theme(legend.position = "none")

ggplotly(points)
```