<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Through the Looking Glass - 2&nbsp; The Ecological Hypotheses</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./eco-hyp-cont.html" rel="next">
<link href="./why-sex.html" rel="prev">
<link href="./images/cover.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="google-site-verification" content="eJHds-HZowhP4fOmzTkps1RTCDKNi3ViSQ2BSaFVA7Y">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Through the Looking Glass - 2&nbsp; The Ecological Hypotheses">
<meta property="og:description" content="">
<meta property="og:image" content="https://iulibscholcomm.github.io/through-the-looking-glass/images/cover.jpg">
<meta property="og:site-name" content="Through the Looking Glass">
<meta name="twitter:title" content="Through the Looking Glass - 2&nbsp; The Ecological Hypotheses">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://iulibscholcomm.github.io/through-the-looking-glass/images/cover.jpg">
<meta name="twitter:creator" content="@curt_lively">
<meta name="twitter:card" content="summary">
<meta name="citation_title" content="Through the Looking Glass: Coevolution, Polymorphism, and Sexual Reproduction">
<meta name="citation_author" content="Curtis Lively">
<meta name="citation_publication_date" content="2023">
<meta name="citation_cover_date" content="2023">
<meta name="citation_year" content="2023">
<meta name="citation_fulltext_html_url" content="https://iulibscholcomm.github.io/through-the-looking-glass/eco-hyp.html">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Literate programming;,citation_author=Donald E. Knuth;,citation_publication_date=1984-05;,citation_cover_date=1984-05;,citation_year=1984;,citation_fulltext_html_url=https://doi.org/10.1093/comjnl/27.2.97;,citation_issue=2;,citation_doi=10.1093/comjnl/27.2.97;,citation_issn=0010-4620;,citation_volume=27;,citation_journal_title=Comput. J.;,citation_publisher=Oxford University Press, Inc.;">
</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./why-sex.html">Part One: Why Cross-Fertilize?</a></li><li class="breadcrumb-item"><a href="./eco-hyp.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Ecological Hypotheses</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/cover.jpg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Through the Looking Glass</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://biology.indiana.edu/about/faculty/lively-curt.html" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-person-circle"></i></a>
    <a href="https://twitter.com/curt_lively" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-twitter"></i></a>
    <a href="https://github.com/IULibScholComm/through-the-looking-glass" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Through-the-Looking-Glass.pdf">
              <i class="bi bi-bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Through-the-Looking-Glass.epub">
              <i class="bi bi-bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Through-the-Looking-Glass.docx">
              <i class="bi bi-bi-file-word pe-1"></i>
            Download Docx
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Front Matter</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Part One: Why Cross-Fertilize?</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./why-sex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Sex?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eco-hyp.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Ecological Hypotheses</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eco-hyp-cont.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Contrasting the Ecological Hypotheses</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rat-red.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">The Ratchet and the Red Queen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Back Matter</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#the-lottery-model" id="toc-the-lottery-model" class="nav-link active" data-scroll-target="#the-lottery-model"><span class="header-section-number">2.1</span> The Lottery Model</a></li>
  <li><a href="#the-tangled-bankfrozen-niche-variation-model" id="toc-the-tangled-bankfrozen-niche-variation-model" class="nav-link" data-scroll-target="#the-tangled-bankfrozen-niche-variation-model"><span class="header-section-number">2.2</span> The Tangled Bank/Frozen Niche-Variation Model</a></li>
  <li><a href="#the-red-queen-hypothesis" id="toc-the-red-queen-hypothesis" class="nav-link" data-scroll-target="#the-red-queen-hypothesis"><span class="header-section-number">2.3</span> The Red Queen Hypothesis</a>
  <ul class="collapse">
  <li><a href="#an-intersection-of-science-and-literature" id="toc-an-intersection-of-science-and-literature" class="nav-link" data-scroll-target="#an-intersection-of-science-and-literature"><span class="header-section-number">2.3.1</span> An intersection of science and literature</a></li>
  <li><a href="#conceptual-roots-of-the-red-queen-hypothesis" id="toc-conceptual-roots-of-the-red-queen-hypothesis" class="nav-link" data-scroll-target="#conceptual-roots-of-the-red-queen-hypothesis"><span class="header-section-number">2.3.2</span> Conceptual roots of the Red Queen Hypothesis</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">2.4</span> Summary</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/IULibScholComm/through-the-looking-glass/edit/main/eco-hyp.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/IULibScholComm/through-the-looking-glass/issues/new" class="toc-action">Report an issue</a></p><p><a href="https://github.com/IULibScholComm/through-the-looking-glass/blob/main/eco-hyp.qmd" class="toc-action">View source</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-eco-hyp" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Ecological Hypotheses</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 17, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig2-1.jpeg" class="img-fluid figure-img" alt="Two tickets and the Red Queen leading Alice around a tree"></p>
</figure>
</div>
<p>The sex/recombination (“sex/rec”) anomaly has attracted some of the best theoretical biologists over the last 50 years, leading to at least two dozen hypotheses to explain selection for recombination and/or the persistence of obligate sexual reproduction in natural populations (Kondrashov 1993). In what follows, I first focus on the ecological hypotheses. The ideas underlying these hypotheses provide a handle for understanding some of the foundational concepts in evolutionary ecology.</p>
<section id="the-lottery-model" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="the-lottery-model"><span class="header-section-number">2.1</span> The Lottery Model</h2>
<p>As part of his book on the evolution of sex, Williams (1975) suggested that sex could be favored in fluctuating abiotic environments. The idea is intuitive: cross-fertilization generates variation among offspring. Hence, in fluctuating environments, sex could increase the probability that some offspring might survive. Williams likened the idea to a unique kind of lottery. For example, he wrote: “Suppose you were offered this choice in a lottery: either you could have several different tickets, or you could have the same number of copies of the same ticket” (p.&nbsp;15). If you choose <em>N</em> copies of the same ticket (asex), and your ticket wins, you get <em>N</em> times the reward. If you choose <em>N</em> different tickets (sex), you increase the probability of winning something, but the reward is smaller. Williams referred to the idea as the aphid-rotifer model, but the idea has since come to be known as the Lottery Model (following Bell 1982), which is a more descriptive phrase.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>In my evolution course, I ask a form of Williams’ question, but with a slight twist:</p>
<blockquote class="blockquote">
<p>If you had a garden, upon which your descendants will depend for many generations to come, would you</p>
<ol type="1">
<li>plant a genetically variable crop, or</li>
<li>a monoculture with a two-fold higher yield?</li>
</ol>
<p>Keep in mind that your descendants will follow your choice.</p>
</blockquote>
<p>Often the students rightfully want some clarification. They ask, for example, “Can we use pesticides?” But every time, most students choose the variable crop. I remind them that selecting the variable crop will reduce their yield by one half. They don’t budge. I re-ask the question, doubling the relative yield for the monoculture from two-fold to four-fold. Then to 10-fold. Occasionally, one of the more risk-prone students will select the 10-fold higher yield, but most do not budge. They want genetic variation. I ask them why. Invariably, they say that the environment is going to change. They want to hedge their bets against an uncertain future.</p>
<p>Indeed, Williams’ Lottery Model is about bet hedging. The gist of bet-hedging in evolutionary theory is that selection can act to reduce the variance in reproductive success over time, even if it also reduces the arithmetic mean across years (review in Philippi and Seger 1989). Suppose, for example, that we have the following data for both a monoculture and a genetically variable polyculture (in arbitrary units). Let’s assume that the variation in yield is driven by annual variation in abiotic factors, such as temperature or precipitation. The effect of planting a polyculture (bet-hedging) can be estimated from the geometric mean, which incorporates the variation in yield over time.</p>
<table class="table">
<thead>
<tr class="header">
<th>Year</th>
<th>Monoculture</th>
<th>Polyculture</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>350</td>
<td>250</td>
</tr>
<tr class="even">
<td>2</td>
<td>400</td>
<td>250</td>
</tr>
<tr class="odd">
<td>3</td>
<td>300</td>
<td>200</td>
</tr>
<tr class="even">
<td>4</td>
<td>100</td>
<td>200</td>
</tr>
<tr class="odd">
<td>5</td>
<td>50</td>
<td>200</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Arithmetic mean</strong></td>
<td><strong>240</strong></td>
<td>220</td>
</tr>
<tr class="even">
<td><strong>Variance</strong><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></td>
<td>19400</td>
<td>600</td>
</tr>
<tr class="odd">
<td><strong>Geometric mean (GM)</strong><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></td>
<td>184</td>
<td><strong>219</strong></td>
</tr>
<tr class="even">
<td><strong>Approximate GM</strong></td>
<td>200</td>
<td><strong>219</strong></td>
</tr>
</tbody>
</table>
<p>In this example, we find that the monoculture has an arithmetic mean of 240, while the polyculture has an arithmetic mean of only 220. So, I might be inclined to plant the monoculture. However, the among-year variance is very high for the monoculture (relative to the polyculture), driven in large part by the low yields in years 4 and 5. By contrast, the geometric mean for the monoculture is 184, while the geometric mean for the polyculture is 219. Based on this, I might be inclined to plant the polyculture, as it reduces the cost of very low yield in bad years. I think the students see this intuitively. Over the long term, it is better to be risk-averse and plant the genetically variable polyculture. What if, for example, the monoculture produced no food in the last year? The geometric mean would be zero. That would be catastrophic.</p>
<p>The effect of variance on the geometric mean (GM) can be seen by an approximation (Stearns 2000):</p>
<p><span class="math display">\[\text{GM} \approx \overline{x} - \frac{\text{var}(x)}{2\overline{x}}\]</span></p>
<p>where <span class="math inline">\(\overline{x}\)</span> is the mean, and var(<span class="math inline">\(x\)</span>) is the variance in <span class="math inline">\(x\)</span>. Note that the approximation is equal to the arithmetic mean when the variance in <span class="math inline">\(x\)</span> is zero. Note too that the geometric mean increases as the variance in <span class="math inline">\(x\)</span> decreases. So, if selection operates to reduce the among-year variance in fitness, the outcome of selection will be reflected by an increase in the geometric mean. In general, evolutionary biologists use the geometric mean (rather than the arithmetic mean) to measure fitness over time.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>Can sex be favored in variable environments as a bet-hedging strategy? It seems like a very sensible idea, provided that the production of genetically variable progeny reduces the among-year variance in offspring survival. But remember, that under a two-fold cost of sex, asexuals can replace large populations of sexuals in tens of generations (see chapter 1). So, if the Lottery Model is correct, significant environmental change must occur very rapidly. The many thousands of years between ice ages, for example, would be too long.</p>
</section>
<section id="the-tangled-bankfrozen-niche-variation-model" class="level2 page-columns page-full" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="the-tangled-bankfrozen-niche-variation-model"><span class="header-section-number">2.2</span> The Tangled Bank/Frozen Niche-Variation Model</h2>
<p>Roughly speaking, the Lottery Model concerns the value of producing diverse offspring in a temporally variable abiotic environment. A different kind of model instead concerns the role of competition for different resource types that vary in space. Let us first consider the Frozen Niche-Variation Hypothesis of Robert Vrijenhoek. The key idea is that the clonal derivatives of sexual ancestors “freeze” some of the genetic variation in the sexual population. This frozen genotype then determines the resource niche of the clone. It seems reasonable to assume that the niche width of a single clone would be relatively narrow compared to the niche width of the genetically diverse sexual population. So, under this idea, a clone could invade a sexual population, and perhaps displace it from one of its many niches. But a single clone could not completely replace the sexual population (Vrijenhoek 1979). This kind of process could explain those situations in which sexual and asexual females coexist, which was a major advance.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>A conceptually similar model was independently developed by Graham Bell: the Tangled Bank Hypothesis (Bell 1982). Bell nabbed the name from the last paragraph of the <em>Origin of Species</em>, in which Darwin imagines life as an “entangled bank” of species interacting in a complex network. The core of the idea can be traced back to Howard Levene’s (1953) pioneering model, which showed that polymorphism could be maintained in a spatially heterogeneous environment provided that different genotypes specialize on different resources. Levene’s model was a major advance, as it showed that genetic diversity could be maintained without heterozygote advantage (<a href="#callout-2.1">Box 2.1</a>). This was also one of the first models to fuse population genetics with ecology. But how does multiple niche polymorphism apply to sex? The idea is that, if selection results in polymorphism, then a genetically diverse sexual population might be resistant to replacement by a clonal lineage that specializes on only one of the available resource types (as also in the Frozen Niche-Variation Model).</p>
<p>Here is how I pose the Tangled Bank idea to my undergraduate students. I start by giving them a choice between two hypothetical resources, which occur in different parts of the room. One is pizza, the other is broccoli. They all choose pizza. The problem, of course, is that the per-person value of the pizza resource declines as the pizza-eating population grows. At some point, there will be an advantage to specializing on broccoli. This could lead to a polymorphic population composed of obligate pizza eaters and obligate broccoli eaters, where (at equilibrium) the value of both resources is the same. Hence, selection for or against a particular strategy depends on the frequency of that strategy in the population. Perhaps this kind of <em>frequency-dependent selection</em> could favor sexual reproduction as a way to diversify offspring in environments where different resource types are patchily distributed in space. This reasoning forms the essence of the Tangled Bank Hypothesis.</p>
<p>One especially interesting aspect of the Tangled Bank Model is that the strength of frequency-dependent selection depends on population density. For example, there would be no selection to utilize the resource of lower value (broccoli) if there were no competition for pizza. This kind of selection, where the advantage to being rare depends on population density, is sometimes referred to as “soft” selection (Wallace 1975).<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> In other words, soft selection is selection that is both frequency-dependent and density-dependent. This idea contrasts nicely with the Lottery Model, where selection is both frequency- and density-independent, which is called “hard” selection. For our purposes, we can use Wallace’s terminology to conceptually separate the Tangled Bank Hypothesis from the Lottery Model <a href="#fig-2-2">Figure&nbsp;<span>2.1</span></a>.</p>
<div id="fig-2-2" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/fig2-2.jpeg" class="img-fluid figure-img" style="width:75.0%" alt=""></p>
<figcaption class="figure-caption margin-caption">Figure&nbsp;2.1: Partitioning the ecological hypotheses for the maintenance of obligate sexual reproduction. The figure is redrawn from Wallace (1975). The inserted blue text shows how the ecological hypotheses fit into Wallace’s matrix for density-dependent selection vs frequency-dependent selection. The Lottery Model relies on hard selection in temporally variable environments. The Tangled Bank relies on soft selection in spatially variable environments. The Red Queen relies on frequency-dependent selection generated by coevolving antagonistic species.</figcaption>
</figure>
</div>
<p>We can think of the contrast like this. Under the Lottery Model, changes in the environment will select against certain genotypes independent of whether they are common or rare. Selection seems unconditional (hard). Under the Tangled Bank, selection is always conditional (soft); there is an advantage to having a rare genotype, but this advantage only accrues under strong competition (high density). Soft selection may not be exactly the best possible phrase, but it contrasts nicely with hard selection.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<p>Two caveats are worth mentioning with respect to soft selection and the Tangled Bank Hypothesis. One is that polymorphism is only stable under a narrow range of patch-types frequencies. In addition, strong tradeoffs are required for the cost and benefits for morphs occupying different patches (Maynard Smith and Hoekstra 1980, Lively 1986a) (see also <a href="https://iulibscholcomm.github.io/through-the-looking-glass/eco-hyp-cont.html#callout-4">Box 3.1</a>). The second caveat is that repeated mutation to asexual reproduction could lead to the accumulation of clonal diversity over time. Once all the niches are occupied by different specialized clones, there would be no advantage to sex. A diverse clonal population could then replace the sexual population (Bell 1982, Vrijenhoek and Parker 2009). This second caveat applies, in general, to any model of sex that relies on frequency-dependent selection. But the ideas could work if mutations to asex are rare. And, as I mentioned, sexuals and asexuals are known to coexist in some populations, which is consistent with the Tangled Bank and Frozen Niche-Variation Hypotheses (Vrijenhoek and Parker 2009). Coexistence, however, is also compatible with the Red Queen hypothesis, which we will now consider.</p>
</section>
<section id="the-red-queen-hypothesis" class="level2 page-columns page-full" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="the-red-queen-hypothesis"><span class="header-section-number">2.3</span> The Red Queen Hypothesis</h2>
<p>The Red Queen Hypothesis is like the Lottery Model in that it focusses on environmental change over time. However, under the Red Queen idea, the change is mediated by changes in coevolving biological antagonists such as parasites, rather than changes in the abiotic environments.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> The distinction is important, as we will see.</p>
<p>It may be helpful to revisit <a href="why-sex.html#fig-1-2">Figure&nbsp;<span>1.2</span></a>, which shows the replacement of a sexual population by a clonal lineage within 25 generations. In this example, the clone was a single genotype, while the sexual population was composed of multiple recombining genotypes, only one of which was shared with the clone. Clearly, as the clone spreads, its genotype would become the most common in the host population. Now suppose that the host population is coevolving with a parasite population, which is composed of multiple strains. Assuming random contact between hosts and parasites, the parasite strain that could infect the most common host genotype would have a selective advantage over parasite strains that could only infect rare host genotypes. Let’s call this more successful parasite strain “strain <strong>A</strong>.” What would happen? It should be easy to see that strain <strong>A</strong> would increase in frequency. The parasite population would evolve.</p>
<p>Now, what if the parasite dramatically reduces the reproductive success of infected hosts? We might expect that, as the parasite evolves to infect the most-common host genotype, the reproductive advantage of the host clone is eroded. Moreover, if the parasite is <em>common and sufficiently virulent</em>, evolution by the parasite could prevent the clone from eliminating the sexual population. Under this scenario, there are at least two possible outcomes. One is that the sexuals and asexuals come to exist in stable frequencies, where the lost fecundity of the clone due to infection is equal to the cost of males, meaning that the mean fitnesses of sexuals and asexuals are equal. On the other hand, if the parasite is highly virulent, the frequencies of sexuals and asexuals can oscillate over time (<a href="#fig-2-3">Figure&nbsp;<span>2.2</span></a> A). Under this second scenario, the new clone initially increases, but it is driven down sharply by infection (<a href="#fig-2-3">Figure&nbsp;<span>2.2</span></a> B). Then, once the clone becomes very rare, it should become less infected than observed in the sexual population (<a href="#fig-2-3">Figure&nbsp;<span>2.2</span></a> B). During this period, there is parasite-mediated selection against sex. Hence, the clone increases in frequency (<a href="#fig-2-3">Figure&nbsp;<span>2.2</span></a> A), only to be driven down again by parasites after it becomes common (<a href="#fig-2-3">Figure&nbsp;<span>2.2</span></a> B). Another cycle begins. <strong>The key point is that parasites do not select against clonal reproduction per se; they only select against common genotypes.</strong> But selection against common host genotypes might be sufficient to prevent fixation of a clone in the short term.</p>
<div id="fig-2-3" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/fig2-3.jpg" class="img-fluid figure-img" alt=""></p>
<figcaption class="figure-caption margin-caption">Figure&nbsp;2.2: Simulation model showing that coevolving parasites can prevent the fixation of asexuals in the short term. <strong>A.</strong> The number of sexual and asexual individuals over time. <strong>B.</strong> The frequency of infection in sexual and asexual individuals over time. The simulation introduces a single clonal genotype into a sexual population at carrying capacity. After the clone becomes common (<strong>A</strong>) the parasites evolve to “target” it for infection (<strong>B</strong>). Note that after the parasites have driven the clone’s frequency down, the asexuals are less infected than the sexuals. Simulation model based on Lively (2009), which treats parasite virulence as a positive function of host density.</figcaption>
</figure>
</div>
<p>This scenario of fluctuating selection for and against sex is just a special case of the more general idea that parasites will select against common genotypes within a diverse, sexual host population. As a rare host genotype becomes common, the parasites genotype that can infect it will be favored by natural selection. If the parasite is virulent (meaning that infection reduces host fitness), the targeted host genotype will decline in frequency, and a new host genotype will begin to increase in frequency. Under this logic, host-parasite coevolution will lead to the oscillation of genotypes in both the host and the parasite populations (<a href="#fig-2-4">Figure&nbsp;<span>2.3</span></a>). These oscillations are now called Red Queen dynamics. Red Queen dynamics can lead to the maintenance of genetic polymorphism in sexual populations, and possibly protect sexual reproduction from replacement by asexual lineages. In addition, Red Queen dynamics could also favor recombination within a sexual population (Peters and Lively 1999, Schmid-Hempel and Jokela 2002, Peters and Lively 2007, Salathe et al.&nbsp;2008). These related ideas are now called the Red Queen Hypothesis (following Bell 1982).</p>
<div id="fig-2-4" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/fig2-4.jpeg" class="img-fluid figure-img" alt=""></p>
<figcaption class="figure-caption margin-caption">Figure&nbsp;2.3: Red Queen dynamics. The frequency of a single host genotype is shown along with the frequency of the only parasite genotype that can infect it. Note that the parasite tracks the host with a time lag. Results were extracted from a simulation of a sexual host population with nine possible genotypes coevolving with an asexual parasite with nine matching genotypes Lively (2009). The dashed line shows the average genotype frequency for hosts and parasites.</figcaption>
</figure>
</div>
<section id="an-intersection-of-science-and-literature" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="an-intersection-of-science-and-literature"><span class="header-section-number">2.3.1</span> An intersection of science and literature</h3>
<p>The name for the Red Queen Hypothesis comes from <em>Through the Looking Glass</em> (Carroll 1872). Here are the relevant bits of the story. After Alice goes through the looking glass (a mirror), she decides to follow a straight path to the top of a hill. But, in following the path, she ends up at her starting point. Talking to herself, she remarks, “But how curiously it twists! It’s more like a corkscrew than a path.” Repeated attempts were unsuccessful. In frustration, Alice addresses a tiger lily amongst a patch of flowers, “I wish you could talk!” The lily informs Alice that all the flowers can talk. The stunned Alice then begins a conversation with the flowers before finally asking, <em>Are there more people in the garden besides me?</em> The rose answers <em>yes, there is someone like you.</em> Alice sets out to follow this person (the Red Queen), but she quickly loses sight of her, and ends up back at her original starting point. Flustered, Alice decides to follow the advice of the rose: “I should advise you to walk the other way.” Alice then quickly finds the Red Queen.</p>
<p>Now it gets especially interesting. Alice mentions to the Red Queen that she would like to “find my way to the top of the hill.” The Red Queen replies: “I could show you hills in comparison with which you’d call that a valley.” Alice protests: “a hill ca’n’t be a valley… That would be nonsense.” This exchange between Alice and the Red Queen now seems prophetic, because, under frequency-dependent selection, locations on the adaptive landscape can rapidly change from fitness peaks to fitness valleys. Perhaps the Red Queen’s statement is correct: hills can become valleys, and valleys can become hills. More specifically, genotypes that were favored by natural selection when rare can become selected against after they become common, leading to a highly dynamic adaptive landscape.</p>
<p>In any case, Alice had clearly entered a crazy world. Straight paths become like corkscrews, progress is made by going the other way, and hills become valleys. Then, suddenly, Alice and the Red Queen began to run: “Alice never could quite make out, in thinking afterwards, how it was that they began: all she remembers is, that they were running hand in hand, and the Queen went so fast that it was all she could do to keep up with her.” During this furious run, Alice notices that they never pass anything. The trees remain in the same place as if they were moving along with them. Alice eventually asks: “Are we nearly there?” The Red Queen replies: “Why, we passed it ten minutes ago! Faster!”</p>
<p>When they finally stop, Alice is surprised to be where they started: “I do believe we have been under this tree the whole time! Everything is just as it was!” The Red Queen replies that of course, and then asks: “What would you have it?” Alice replies that she would have expected to get somewhere else after running for a long time. The Red Queen then replies with this very famous quote: “Now, <em>here</em>, you see, it takes all the running <em>you</em> can do to keep in the same place.” It is a perfect metaphor for host-parasite coevolution<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>. Host and parasite genotypes might oscillate as if they were running to stay in the same place.</p>
<p>It seems unlikely that Lewis Carroll had coevolution in mind when writing these passages. But he was a mathematician at Oxford University (his given name was Charles Dodgson), and at least one author has shown how his writings can be seen as metaphors for mathematical problems (Bayley 2009, 2010). Along these lines, mathematician Sanderson M. Smith has suggested that <a href="http://www.herkimershideaway.org/writings/carroll.htm">Carroll simply inverted the equation for speed from “speed = distance/time” to “speed = time/distance”</a>. Upon rearrangement, the latter gives “distance = time/speed.” Hence you must run very fast to stay in the same place. But how does the shifting landscape fit in? And why did Alice have to go the other way to meet the Red Queen? I would love to know.</p>
<p>It is perhaps worth pointing out that the phrase “Red Queen Hypothesis” can have two different meanings to evolutionary biologists. In the early 1970s, Leigh van Valen was grappling with data showing that the probability of extinction in very different organisms was independent of the age of the lineage. He reasoned that, in coevolutionary interactions, the probability of one species driving the other species extinct could, in fact, be independent of lineage age (Van Valen 1973). It thus seems reasonable to suggest that both antagonists must run (coevolve) as fast as they can to prevent extinction. Graham Bell repurposed the phrase to mean within-population oscillations in host and parasite genotypes (Bell 1982). Hence, Van Valen’s idea is about macroevolution (speciation/extinction), while Bell’s idea is about microevolution. Even though van Valen’s use of the Red Queen metaphor was published first, I will use Bell’s microevolutionary meaning, as it perfectly captures the oscillating nature of genotype frequencies during host-parasite coevolution.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
</section>
<section id="conceptual-roots-of-the-red-queen-hypothesis" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="conceptual-roots-of-the-red-queen-hypothesis"><span class="header-section-number">2.3.2</span> Conceptual roots of the Red Queen Hypothesis</h3>
<p>Part of my goal is to show science as a process. As such it seems reasonable to discuss the origins of the Red Queen idea. One of the earliest statements alluding to the Red Queen Hypothesis came from W.D. Hamilton (1975). Hamilton was reviewing the books by Williams (1975) and Ghiselin (1974) for the <em>Quarterly Review of Biology</em>. Throughout the review, the reader can feel Hamilton’s frustration with their arguments. Towards the end, he makes this very abstract suggestion: “…it seems to me that we need environmental fluctuations around a trend line of change” and “For the source of these we may look to fluctuations and periodicities … generated by life itself.”</p>
<p>The quote does not specifically refer to parasites, but it does suggest that coevolutionary interactions, in general, could play a role in selecting for sex and recombination. In his memoirs, Hamilton clears this up, writing: “At that stage when I wrote the review, although I had not seen the particular relevance that parasitism might have, I had for many years seen sex looming ahead and had reached a stage of being excited by the possible primary role of biotic interaction. I had decided that it was in aspects of the interspecies struggle, and not survival in an inanimate environment, that I had to search for the main factor. Adaptation to new physical habitats might be made possible through sexuality but these adaptations could not be the main reason for its existence (Hamilton 2001).”</p>
<p>Note that, here, Hamilton is specifically contrasting host-parasite coevolution with the Lottery Model, which relies on random changes in “physical habitats.”</p>
<p>At about the same time, a plant population biologist, Don Levin, was also writing on the paradox of sex/rec. In his paper, Levin specifically identified pathogens as a possible force selecting for recombination (Levin 1975): “I propose that the persistent tracking of plant hosts by multiple pathogens and herbivores is a prime factor which prohibits the congealing of the genomes of species, especially those in closed communities.”</p>
<p>Boom! By “prohibit the congealing of genomes,” Levin means, “selects for recombination.” The reference to “closed communities” means species that are tightly coevolving in the absence of homogenizing gene flow. This quote seems to be the first to specifically identify coevolving pathogens as a primary source of selection favoring the mixing of genomes. Levin’s idea was quickly followed by important conceptual contributions by Glesener &amp; Tilman (1978)<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a>, Jaenike (1978)<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a>, and Lloyd (1980). In particular, Lloyd writes: “… biological interactions are more likely than unpredictable physical conditions to provide the kind of relentless, repetitive change that is necessary for sexual parents to be selected because of the genetic diversity that sex engenders.”</p>
<p>Lloyd then turns this abstract idea into a specific prediction, which I would later test: “If this proves to be so, we will then be able to examine whether the occurrence of asexual reproduction is correlated with relaxation of the biological hostility of the environment.” Notice that, in the quotes presented above, both Hamilton and Lloyd were specifically predicting that coevolution is more important in selecting for sex than uncertain physical environments. But it is reasonable to ask, does it really matter? Aren’t both ideas fundamentally about bet hedging in uncertain environments? Yes: I think both ideas are about bet hedging. But the distinction still matters. The Lottery Model is about random shifts in the direction of selection; there is no selection against common genotypes unless the environment changes by chance in a way that disfavors them. By contrast, under the Red Queen, selection is frequency dependent. In fact, selection against common genotypes is the core of the model. Hence, the critical difference between the models is not so much about bet hedging but whether selection for sex/rec is directional (but randomly changing directions, a lottery) or frequency dependent (Red Queen). For example, parasites could be a source of directional selection for sex if they randomly changed which host genotypes they attacked. To my mind, that would be a Lottery Model. The Red Queen Hypothesis requires frequency-dependent selection generated by interactions between species.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a> This is an important distinction.</p>
<p>Taking this view, the Red Queen Hypothesis may seem more closely related to the Tangled Bank model than to the Lottery Model, as both the Red Queen and the Tangled Bank rely on frequency-dependent selection. But the critical distinction here is that selection against common genotypes under the Tangled Bank relies on intraspecific competition in populations at carrying capacity (soft selection). The Red Queen relies on interspecific antagonistic coevolution, leading to parasite-mediated selection against common host genotypes.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></p>
<p>In any case, looking back, it seems clear that the architects of the ecological hypotheses had two inter-related things in mind:</p>
<ol type="1">
<li>How can we explain sex/rec, and</li>
<li>How do we understand the biogeographic and phylogenetic distributions of asexual reproduction?</li>
</ol>
<p>As an evolutionary ecologist, I was drawn to the confluence of these questions. But other ideas were also interesting, such as the idea that sexual reproduction is favored because it reduces the interference between alleles at different loci (review in Otto 2021). I will cover some special cases of this latter idea in <a href="rat-red.html"><span>Chapter&nbsp;4</span></a>.<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a></p>
</section>
</section>
<section id="summary" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="summary"><span class="header-section-number">2.4</span> Summary</h2>
<ol type="1">
<li><p>Three ecological hypotheses have been proposed to explain the persistence of cross-fertilization in the face of competition with uniparental reproductive strategies such as parthenogenesis or self-fertilization (following Bell 1982).</p></li>
<li><p>The Lottery Model is based on the possible advantages of diversifying offspring facing uncertain changes in the abiotic environment. Here selection is independent of both density and frequency.</p></li>
<li><p>The Tangled Bank and Frozen Niche-Variation Hypotheses are based on competition for resources when multiple resource types co-occur. Selection is frequency dependent, but the advantage to rare types only occurs when intraspecific competition is intense.</p></li>
<li><p>The Red Queen Hypothesis relies on parasite-mediated selection against common host genotypes. Such selection, when strong, can result in oscillatory changes in parasite and host alleles. These oscillations are sometimes called Red Queen dynamics.</p></li>
<li><p>A bet-hedging strategy reduces the variance in reproductive success over time, even if it reduces the arithmetic mean. Sexual reproduction under the Lottery Model is clearly a bet-hedging strategy. The Red Queen idea can perhaps also be seen as bet hedging.</p></li>
</ol>
<div id="callout-3" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Box 2.1. Levene’s model of multiple niche polymorphism.
</div>
</div>
<div class="callout-body-container callout-body">
<p>It was widely thought that heterozygote advantage was required to maintain polymorphism at a single locus with two alleles. In the introduction to his paper, Levene wonders “…whether it was in fact possible to have an equilibrium without the heterozygote being superior in any single niche.” The paper is not easy to follow, even though the algebra is not difficult. Here I try to simplify the presentation.</p>
<p>Levene first assumes that the proportion of survivors coming from the <span class="math inline">\(i^{th}\)</span> niche is constant <span class="math inline">\((q)\)</span>, independent of the genotypic composition of the niche (i.e., soft selection). He then assumes that the heterozygote has a relative fitness of 1 in all niches, giving <span class="math inline">\(W_{AB} = 1\)</span>. Let <span class="math inline">\(q\)</span> be the frequency of allele A, and let (<span class="math inline">\(1 - q\)</span>) be the frequency of allele B. The frequency of allele A in the next generation, <span class="math inline">\(q'\)</span>, is then</p>
<p><span class="math display">\[q^{'} = \sum_{}^{}c_{i}\frac{q^{2}W_{AAi} + q(1 - q)}{q^{2}W_{AAi} + 2q(1 - q) + (1 - q)^{2}W_{BBi}}\]</span></p>
<p>The change in <span class="math inline">\(q\)</span> is simply <span class="math inline">\(\mathrm{\Delta}q = q^{'} - q\)</span>. Under these assumptions, Levene showed that A allele will increase when rare (barring genetic drift) when |</p>
<p><span class="math display">\[\frac{1}{\sum_{}^{}{c_{i}\frac{1}{W_{AAi}}}} &lt; 1\]</span></p>
<p>where the left-hand side gives the harmonic mean fitness for genotype AA over all niches. The right-hand-side of the equation gives the harmonic mean fitness of the heterozygous genotype, AB, which is equal to 1. Similarly, the B allele will increase when rare when</p>
<p><span class="math display">\[\frac{1}{\sum_{}^{}{c_{i}\frac{1}{W_{BBi}}}} &lt; 1\]</span></p>
<p>where the left-hand side gives the harmonic mean fitness for genotype BB over all niches. A genetic polymorphism is expected if both alleles can increase when rare, hence <strong>polymorphism is expected when, in general, when the harmonic mean fitness for the heterozygote is greater than the harmonic mean fitness for either homozygote</strong>.</p>
<p>But does this require that the AB genotype is the most fit in at least one niche? Levene gives a specific example to answer this question. He assumes two niches, where the proportion of survivors from both niches is equal (i.e., <span class="math inline">\(c_{1} = c_{2} = 0.5\)</span>). He then assumes genotypic fitness values, as given in the following table. It is important to note that the heterozygous genotype is not the most fit genotype in either niche.</p>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 26%">
<col style="width: 27%">
<col style="width: 14%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Genotype</th>
<th><strong>Fitness Niche 1</strong></th>
<th><strong>Fitness Niche 2</strong></th>
<th><strong>Arithmetic mean</strong></th>
<th><strong>Harmonic mean</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>AA</strong></td>
<td><span class="math inline">\(W_{AA1}\)</span> = 1.50</td>
<td><span class="math inline">\(W_{AA2}\)</span> = 0.67</td>
<td>1.09</td>
<td>0.93</td>
</tr>
<tr class="even">
<td><strong>AB</strong></td>
<td><span class="math inline">\(W_{AB1}\)</span> = 1.00</td>
<td><span class="math inline">\(W_{AB2}\)</span> = 1.00</td>
<td>1.00</td>
<td>1.00</td>
</tr>
<tr class="odd">
<td><strong>BB</strong></td>
<td><span class="math inline">\(W_{BB1}\)</span> = 0.67</td>
<td><span class="math inline">\(W_{BB2}\)</span> = 1.50</td>
<td>1.09</td>
<td>0.93</td>
</tr>
</tbody>
</table>
<p>For this example, the harmonic mean fitness for the heterozygote is greater than the harmonic mean fitness for either homozygote, thus meeting the conditions given by the equations above. Thus, the answer to Levene’s question is yes. It is possible to have a genetic polymorphism without having heterozygote advantage in any single niche. And, interestingly, the polymorphism is expected even though the arithmetic mean fitness of the heterozygote is less than the arithmetic mean fitness of either homozygote. Finally, based on this example, it seems that a trade-off is required, such that the AA genotype does best in one niche, and the BB genotype does best in the other niche.</p>
<p>Nonetheless, Levene’s result suggests that overdominance for harmonic mean fitness is required for multiple niche polymorphism (Prout 1968). However, Timothy Prout showed that a polymorphism could be stable, even if one allele is dominate, thus ruling out any kind of overdominance (Prout 1968). Let both the AA and AB genotypes have a fitness of 1 in both niches. Let the BB genotype have a fitness of 0.5 in niche 1 and a fitness of 1.67 in niche 2. Assuming as above that both patches are equally common, we get the following table.</p>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 26%">
<col style="width: 27%">
<col style="width: 14%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Genotype</th>
<th><strong>Fitness Niche 1</strong></th>
<th><strong>Fitness Niche 2</strong></th>
<th><strong>Arithmetic mean</strong></th>
<th><strong>Harmonic mean</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>AA</strong></td>
<td><span class="math inline">\(W_{AA1}\)</span> = 1.00</td>
<td><span class="math inline">\(W_{AA2}\)</span> = 1.00</td>
<td>1.00</td>
<td>1.00</td>
</tr>
<tr class="even">
<td><strong>AB</strong></td>
<td><span class="math inline">\(W_{AB1}\)</span> = 1.00</td>
<td><span class="math inline">\(W_{AB2}\)</span> = 1.00</td>
<td>1.00</td>
<td>1.00</td>
</tr>
<tr class="odd">
<td><strong>BB</strong></td>
<td><span class="math inline">\(W_{BB1}\)</span> = 0.50</td>
<td><span class="math inline">\(W_{BB2}\)</span> = 1.67</td>
<td>1.09</td>
<td>0.77</td>
</tr>
</tbody>
</table>
<p>Prout showed that there would be a stable multiple niche polymorphism, even under complete dominance, provided that the arithmetic mean fitness for BB is greater than 1, and that the harmonic mean fitness for the BB genotype is less than 1. So, clearly, overdominance for harmonic mean fitness is not required for a stable polymorphism.<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a></p>
<p>The plot below shows <span class="math inline">\(\mathrm{\Delta}q\)</span> as a function of <span class="math inline">\(q\)</span> for Prout’s model of dominance. Note that <span class="math inline">\(\mathrm{\Delta}q\)</span> is positive when <span class="math inline">\(q\)</span> is near zero, and that <span class="math inline">\(\mathrm{\Delta}q\)</span> is negative when <span class="math inline">\(q\)</span> is near 1. There is an interior equilibrium near <span class="math inline">\(q = 0.5\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig2-5.jpg" class="img-fluid figure-img" style="width:65.0%" alt=""></p>
</figure>
</div>
<!--The papers by Levene (1953) and Prout (1968) helped to lay the foundation for the fusion of population genetics and population ecology.-->
</div>
</div>


<!-- -->

</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>See Bell (1982) for a deeper historical view of the Lottery Model, which involves contributions by Maynard Smith and others, including Williams. I have tried to distill it down to a simple bet-hedging model here. The original formulation is more complex.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The variance in <span class="math inline">\(x\)</span> is equal to the average of the squared deviations from the mean: <span class="math inline">\(var(x) = \frac{1}{N}\sum_{i = 1}^{N}{(x_{i} - \overline{x})^{2}}\)</span><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The geometric mean is the <span class="math inline">\(N^{th}\)</span> root of the product of <span class="math inline">\(N\)</span> observations. Compared to the arithmetic mean, the geometric mean gives more weight to small values.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The bet-hedging idea dates to Daniel Bernoulli, a mathematical physicist, writing in 1738. Steve Stearns (2000) provides an important, fascinating review of how evolutionary biologists (beginning with Cohen (1966)) and economists, have borrowed from Bernoulli’s conceptual framework.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Vrijenhoek studied the coexistence of sexual fish with multiple clonal genotypes of asexual congeners in natural populations. He mainly envisioned the Frozen Niche Hypothesis as a model to explain the coexistence of multiple clones, but it can also explain the coexistence of sexual and asexual modes of reproduction if clonal diversity is low, and the clones do not compete strongly. See, for example pages 112-113 in Vrijenhoek and Parker (2009): “The Frozen Niche-Variation Model (Vrijenhoek 1978, 1979) was directly stimulated by Roughgarden’s (1972) ideas and a need to explain the stable coexistence of* Poeciliopsis *fish clones in spatially heterogeneous desert streams (Vrijenhoek 1978).”<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Soft selection in theoretical population genetics can also mean that the contribution of offspring from different demes in a metapopulation is unrelated to differences in mean fitness among demes.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Wallace (1975) explains that the source of the terms “soft” and “hard” stem from financial discussions of soft currencies vs hard currencies in monetary exchanges. Soft currencies only have value within their home country. In contrast, hard currencies can be exchanged overseas for currencies with similar buying power.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>I use “parasite” here in the ecological sense to include any organism that lives in, or on, its host, provided it reduces the survivorship and/or fecundity of its host. As such, the term includes both macroparasites (such as worms) and microparasites (such as protozoans, bacteria, and viruses).<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>The intersection between science and literature is not restricted to selection for or against sex. For a fascinating essay on how the biology of parasites meets literature, see Justyna Jajszczok’s dissertation (Jajszczok 2017).<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>I. M. Lerner used the Red Queen metaphor as early as 1954, with respect to the selection needed to maintain genetic homeostasis: “The <em>Alice in Wonderland</em> situation in which ‘it takes all the running you can do to stay in the same place’ arises when a stationary level of performance can be maintained only by application of the maximum selection possible…” (See page 117 in Lerner (1954)).<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>For example, Glesener and Tilman write: “Thus, sexuality not only is favored under changed conditions but is, itself, capable of changing the conditions. The sexuality of an organism’s competitors, predators, parasites, etc., will greatly increase the selective pressure for sexuality on that organism as well.”<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Jaenike focuses more on the recycling of genotypes: “My hypothesis differs from Levin’s in that sex and recombination are advantageous not to produce novel genotypes as such, but to produce rare genotypes, of which novel ones are only a subset.”<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>I use “frequency-dependent” selection here to mean selection against common genotypes. A more accurate phrase would be “negative frequency-dependent” selection.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>This is not meant to imply, however, that the strength of parasite-mediated selection under the Red Queen Hypothesis must be independent of population size. Indeed, as we will see, there are good reasons to think that the strength of parasite-mediated selection depends on host density.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>The basic idea comes from a paper by Hill and Robertson (1966), and is often called the Hill-Robertson effect (following Felsenstein 1974). A broader framework, housed under the more intuitive phrase “selective interference,” was recently given by Sarah Otto as part of a keynote lecture given to the American Genetic Association (Otto 2021).<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>The harmonic mean is not intuitive to most Biology students. So, I ask them this question: if you had a score of 100 on your first exam, and a score of 60 on your second exam, would you rather have your final grade calculated as the arithmetic mean or the harmonic mean of the two scores? After some thought, they all pick the arithmetic mean. That is because the harmonic mean weights low scores more heavily than high scores.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp("https:\/\/iulibscholcomm\.github\.io\/through-the-looking-glass");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./why-sex.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Sex?</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./eco-hyp-cont.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Contrasting the Ecological Hypotheses</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1"></a><span class="al">![](images/fig2-1.jpeg)</span>{fig-align="center" fig-alt="Two tickets and the Red Queen leading Alice around a tree"}</span>
<span id="cb1-2"><a href="#cb1-2"></a></span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="fu"># The Ecological Hypotheses {#sec-eco-hyp}</span></span>
<span id="cb1-4"><a href="#cb1-4"></a></span>
<span id="cb1-5"><a href="#cb1-5"></a>The sex/recombination ("sex/rec") anomaly has attracted some of the best theoretical biologists over the last 50 years, leading to at least two dozen hypotheses to explain selection for recombination and/or the persistence of obligate sexual reproduction in natural populations (Kondrashov 1993). In what follows, I first focus on the ecological hypotheses. The ideas underlying these hypotheses provide a handle for understanding some of the foundational concepts in evolutionary ecology.  </span>
<span id="cb1-6"><a href="#cb1-6"></a></span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="fu">## The Lottery Model</span></span>
<span id="cb1-8"><a href="#cb1-8"></a></span>
<span id="cb1-9"><a href="#cb1-9"></a>As part of his book on the evolution of sex, Williams (1975) suggested that sex could be favored in fluctuating abiotic environments. The idea is intuitive: cross-fertilization generates variation among offspring. Hence, in fluctuating environments, sex could increase the probability that some offspring might survive. Williams likened the idea to a unique kind of lottery. For example, he wrote: "Suppose you were offered this choice in a lottery: either you could have several different tickets, or you could have the same number of copies of the same ticket" (p. 15). If you choose *N* copies of the same ticket (asex), and your ticket wins, you get *N* times the reward. If you choose *N* different tickets (sex), you increase the probability of winning something, but the reward is smaller. Williams referred to the idea as the aphid-rotifer model, but the idea has since come to be known as the Lottery Model (following Bell 1982), which is a more descriptive phrase.<span class="ot">[^1]</span>  </span>
<span id="cb1-10"><a href="#cb1-10"></a></span>
<span id="cb1-11"><a href="#cb1-11"></a>In my evolution course, I ask a form of Williams' question, but with a slight twist:  </span>
<span id="cb1-12"><a href="#cb1-12"></a></span>
<span id="cb1-13"><a href="#cb1-13"></a><span class="at">&gt; If you had a garden, upon which your descendants will depend for many generations to come, would you</span></span>
<span id="cb1-14"><a href="#cb1-14"></a><span class="at">&gt; </span></span>
<span id="cb1-15"><a href="#cb1-15"></a><span class="at">&gt; 1. plant a genetically variable crop, or</span></span>
<span id="cb1-16"><a href="#cb1-16"></a><span class="at">&gt; 2. a monoculture with a two-fold higher yield?</span>  </span>
<span id="cb1-17"><a href="#cb1-17"></a><span class="at">&gt;</span></span>
<span id="cb1-18"><a href="#cb1-18"></a><span class="at">&gt; Keep in mind that your descendants will follow your choice. </span></span>
<span id="cb1-19"><a href="#cb1-19"></a></span>
<span id="cb1-20"><a href="#cb1-20"></a>Often the students rightfully want some clarification. They ask, for example, “Can we use pesticides?”  But every time, most students choose the variable crop. I remind them that selecting the variable crop will reduce their yield by one half. They don't budge. I re-ask the question, doubling the relative yield for the monoculture from two-fold to four-fold. Then to 10-fold. Occasionally, one of the more risk-prone students will select the 10-fold higher yield, but most do not budge. They want genetic variation. I ask them why. Invariably, they say that the environment is going to change. They want to hedge their bets against an uncertain future. </span>
<span id="cb1-21"><a href="#cb1-21"></a></span>
<span id="cb1-22"><a href="#cb1-22"></a>Indeed, Williams' Lottery Model is about bet hedging. The gist of bet-hedging in evolutionary theory is that selection can act to reduce the variance in reproductive success over time, even if it also reduces the arithmetic mean across years (review in Philippi and Seger 1989). Suppose, for example, that we have the following data for both a monoculture and a genetically variable polyculture (in arbitrary units). Let’s assume that the variation in yield is driven by annual variation in abiotic factors, such as temperature or precipitation. The effect of planting a polyculture (bet-hedging) can be estimated from the geometric mean, which incorporates the variation in yield over time.   </span>
<span id="cb1-23"><a href="#cb1-23"></a></span>
<span id="cb1-24"><a href="#cb1-24"></a>| Year | Monoculture | Polyculture |</span>
<span id="cb1-25"><a href="#cb1-25"></a>|------|-------------|-------------|</span>
<span id="cb1-26"><a href="#cb1-26"></a>| 1 | 350 | 250 |</span>
<span id="cb1-27"><a href="#cb1-27"></a>| 2 | 400 | 250 |</span>
<span id="cb1-28"><a href="#cb1-28"></a>| 3 | 300 | 200 |</span>
<span id="cb1-29"><a href="#cb1-29"></a>| 4 | 100 | 200 |</span>
<span id="cb1-30"><a href="#cb1-30"></a>| 5 | 50 | 200 |</span>
<span id="cb1-31"><a href="#cb1-31"></a>|   |     |     |</span>
<span id="cb1-32"><a href="#cb1-32"></a>| **Arithmetic mean** | **240** | 220 |</span>
<span id="cb1-33"><a href="#cb1-33"></a>| **Variance**<span class="ot">[^2]</span> | 19400 | 600 |</span>
<span id="cb1-34"><a href="#cb1-34"></a>| **Geometric mean (GM)**[^3] | 184 | **219** |</span>
<span id="cb1-35"><a href="#cb1-35"></a>| **Approximate GM** | 200 | **219** |</span>
<span id="cb1-36"><a href="#cb1-36"></a></span>
<span id="cb1-37"><a href="#cb1-37"></a><span class="in">            </span></span>
<span id="cb1-38"><a href="#cb1-38"></a>In this example, we find that the monoculture has an arithmetic mean of 240, while the polyculture has an arithmetic mean of only 220. So, I might be inclined to plant the monoculture. However, the among-year variance is very high for the monoculture (relative to the polyculture), driven in large part by the low yields in years 4 and 5. By contrast, the geometric mean for the monoculture is 184, while the geometric mean for the polyculture is 219. Based on this, I might be inclined to plant the polyculture, as it reduces the cost of very low yield in bad years. I think the students see this intuitively. Over the long term, it is better to be risk-averse and plant the genetically variable polyculture. What if, for example, the monoculture produced no food in the last year?  The geometric mean would be zero. That would be catastrophic. </span>
<span id="cb1-39"><a href="#cb1-39"></a></span>
<span id="cb1-40"><a href="#cb1-40"></a>The effect of variance on the geometric mean (GM) can be seen by an approximation (Stearns 2000):</span>
<span id="cb1-41"><a href="#cb1-41"></a></span>
<span id="cb1-42"><a href="#cb1-42"></a>$$\text{GM} \approx \overline{x} - \frac{\text{var}(x)}{2\overline{x}}$$</span>
<span id="cb1-43"><a href="#cb1-43"></a></span>
<span id="cb1-44"><a href="#cb1-44"></a>where $\overline{x}$ is the mean, and var($x$) is the variance in $x$. Note that the approximation is equal to the arithmetic mean when the variance in $x$ is zero. Note too that the geometric mean increases as the variance in $x$ decreases. So, if selection operates to reduce the among-year variance in fitness, the outcome of selection will be reflected by an increase in the geometric mean. In general, evolutionary biologists use the geometric mean (rather than the arithmetic mean) to measure fitness over time.<span class="ot">[^4]</span></span>
<span id="cb1-45"><a href="#cb1-45"></a></span>
<span id="cb1-46"><a href="#cb1-46"></a>Can sex be favored in variable environments as a bet-hedging strategy?  It seems like a very sensible idea, provided that the production of genetically variable progeny reduces the among-year variance in offspring survival. But remember, that under a two-fold cost of sex, asexuals can replace large populations of sexuals in tens of generations (see chapter 1). So, if the Lottery Model is correct, significant environmental change must occur very rapidly. The many thousands of years between ice ages, for example, would be too long. </span>
<span id="cb1-47"><a href="#cb1-47"></a></span>
<span id="cb1-48"><a href="#cb1-48"></a><span class="fu">## The Tangled Bank/Frozen Niche-Variation Model</span></span>
<span id="cb1-49"><a href="#cb1-49"></a></span>
<span id="cb1-50"><a href="#cb1-50"></a>Roughly speaking, the Lottery Model concerns the value of producing diverse offspring in a temporally variable abiotic environment. A different kind of model instead concerns the role of competition for different resource types that vary in space. Let us first consider the Frozen Niche-Variation Hypothesis of Robert Vrijenhoek. The key idea is that the clonal derivatives of sexual ancestors "freeze" some of the genetic variation in the sexual population. This frozen genotype then determines the resource niche of the clone. It seems reasonable to assume that the niche width of a single clone would be relatively narrow compared to the niche width of the genetically diverse sexual population. So, under this idea, a clone could invade a sexual population, and perhaps displace it from one of its many niches. But a single clone could not completely replace the sexual population (Vrijenhoek 1979). This kind of process could explain those situations in which sexual and asexual females coexist, which was a major advance.<span class="ot">[^5]</span></span>
<span id="cb1-51"><a href="#cb1-51"></a></span>
<span id="cb1-52"><a href="#cb1-52"></a>A conceptually similar model was independently developed by Graham Bell: the Tangled Bank Hypothesis (Bell 1982). Bell nabbed the name from the last paragraph of the *Origin of Species*, in which Darwin imagines life as an "entangled bank" of species interacting in a complex network. The core of the idea can be traced back to Howard Levene's (1953) pioneering model, which showed that polymorphism could be maintained in a spatially heterogeneous environment provided that different genotypes specialize on different resources. Levene's model was a major advance, as it showed that genetic diversity could be maintained without heterozygote advantage (<span class="co">[</span><span class="ot">Box 2.1</span><span class="co">](#callout-2.1)</span>). This was also one of the first models to fuse population genetics with ecology. But how does multiple niche polymorphism apply to sex?  The idea is that, if selection results in polymorphism, then a genetically diverse sexual population might be resistant to replacement by a clonal lineage that specializes on only one of the available resource types (as also in the Frozen Niche-Variation Model).</span>
<span id="cb1-53"><a href="#cb1-53"></a></span>
<span id="cb1-54"><a href="#cb1-54"></a>Here is how I pose the Tangled Bank idea to my undergraduate students. I start by giving them a choice between two hypothetical resources, which occur in different parts of the room. One is pizza, the other is broccoli. They all choose pizza. The problem, of course, is that the per-person value of the pizza resource declines as the pizza-eating population grows. At some point, there will be an advantage to specializing on broccoli. This could lead to a polymorphic population composed of obligate pizza eaters and obligate broccoli eaters, where (at equilibrium) the value of both resources is the same. Hence, selection for or against a particular strategy depends on the frequency of that strategy in the population. Perhaps this kind of *frequency-dependent selection* could favor sexual reproduction as a way to diversify offspring in environments where different resource types are patchily distributed in space. This reasoning forms the essence of the Tangled Bank Hypothesis. </span>
<span id="cb1-55"><a href="#cb1-55"></a></span>
<span id="cb1-56"><a href="#cb1-56"></a>One especially interesting aspect of the Tangled Bank Model is that the strength of frequency-dependent selection depends on population density. For example, there would be no selection to utilize the resource of lower value (broccoli) if there were no competition for pizza. This kind of selection, where the advantage to being rare depends on population density, is sometimes referred to as "soft" selection (Wallace 1975).<span class="ot">[^6]</span> In other words, soft selection is selection that is both frequency-dependent and density-dependent. This idea contrasts nicely with the Lottery Model, where selection is both frequency- and density-independent, which is called "hard" selection. For our purposes, we can use Wallace's terminology to conceptually separate the Tangled Bank Hypothesis from the Lottery Model @fig-2-2.</span>
<span id="cb1-57"><a href="#cb1-57"></a></span>
<span id="cb1-58"><a href="#cb1-58"></a><span class="al">![Partitioning the ecological hypotheses for the maintenance of obligate sexual reproduction. The figure is redrawn from Wallace (1975). The inserted blue text shows how the ecological hypotheses fit into Wallace’s matrix for density-dependent selection vs frequency-dependent selection. The Lottery Model relies on hard selection in temporally variable environments. The Tangled Bank relies on soft selection in spatially variable environments. The Red Queen relies on frequency-dependent selection generated by coevolving antagonistic species.](images/fig2-2.jpeg)</span>{fig-alt="" width=75% #fig-2-2}</span>
<span id="cb1-59"><a href="#cb1-59"></a></span>
<span id="cb1-60"><a href="#cb1-60"></a>We can think of the contrast like this. Under the Lottery Model, changes in the environment will select against certain genotypes independent of whether they are common or rare. Selection seems unconditional (hard). Under the Tangled Bank, selection is always conditional (soft); there is an advantage to having a rare genotype, but this advantage only accrues under strong competition (high density). Soft selection may not be exactly the best possible phrase, but it contrasts nicely with hard selection.<span class="ot">[^7]</span></span>
<span id="cb1-61"><a href="#cb1-61"></a></span>
<span id="cb1-62"><a href="#cb1-62"></a>Two caveats are worth mentioning with respect to soft selection and the Tangled Bank Hypothesis. One is that polymorphism is only stable under a narrow range of patch-types frequencies. In addition, strong tradeoffs are required for the cost and benefits for morphs occupying different patches (Maynard Smith and Hoekstra 1980, Lively 1986a) (see also <span class="co">[</span><span class="ot">Box 3.1</span><span class="co">](https://iulibscholcomm.github.io/through-the-looking-glass/eco-hyp-cont.html#callout-4)</span>). The second caveat is that repeated mutation to asexual reproduction could lead to the accumulation of clonal diversity over time. Once all the niches are occupied by different specialized clones, there would be no advantage to sex. A diverse clonal population could then replace the sexual population (Bell 1982, Vrijenhoek and Parker 2009). This second caveat applies, in general, to any model of sex that relies on frequency-dependent selection. But the ideas could work if mutations to asex are rare. And, as I mentioned, sexuals and asexuals are known to coexist in some populations, which is consistent with the Tangled Bank and Frozen Niche-Variation Hypotheses (Vrijenhoek and Parker 2009). Coexistence, however, is also compatible with the Red Queen hypothesis, which we will now consider. </span>
<span id="cb1-63"><a href="#cb1-63"></a></span>
<span id="cb1-64"><a href="#cb1-64"></a><span class="fu">## The Red Queen Hypothesis</span></span>
<span id="cb1-65"><a href="#cb1-65"></a></span>
<span id="cb1-66"><a href="#cb1-66"></a>The Red Queen Hypothesis is like the Lottery Model in that it focusses on environmental change over time. However, under the Red Queen idea, the change is mediated by changes in coevolving biological antagonists such as parasites, rather than changes in the abiotic environments.<span class="ot">[^8]</span> The distinction is important, as we will see.</span>
<span id="cb1-67"><a href="#cb1-67"></a></span>
<span id="cb1-68"><a href="#cb1-68"></a>It may be helpful to revisit @fig-1-2, which shows the replacement of a sexual population by a clonal lineage within 25 generations. In this example, the clone was a single genotype, while the sexual population was composed of multiple recombining genotypes, only one of which was shared with the clone. Clearly, as the clone spreads, its genotype would become the most common in the host population. Now suppose that the host population is coevolving with a parasite population, which is composed of multiple strains. Assuming random contact between hosts and parasites, the parasite strain that could infect the most common host genotype would have a selective advantage over parasite strains that could only infect rare host genotypes. Let's call this more successful parasite strain "strain **A**." What would happen? It should be easy to see that strain **A** would increase in frequency. The parasite population would evolve.</span>
<span id="cb1-69"><a href="#cb1-69"></a></span>
<span id="cb1-70"><a href="#cb1-70"></a>Now, what if the parasite dramatically reduces the reproductive success of infected hosts?  We might expect that, as the parasite evolves to infect the most-common host genotype, the reproductive advantage of the host clone is eroded. Moreover, if the parasite is *common and sufficiently virulent*, evolution by the parasite could prevent the clone from eliminating the sexual population. Under this scenario, there are at least two possible outcomes. One is that the sexuals and asexuals come to exist in stable frequencies, where the lost fecundity of the clone due to infection is equal to the cost of males, meaning that the mean fitnesses of sexuals and asexuals are equal. On the other hand, if the parasite is highly virulent, the frequencies of sexuals and asexuals can oscillate over time (@fig-2-3 A). Under this second scenario, the new clone initially increases, but it is driven down sharply by infection (@fig-2-3 B). Then, once the clone becomes very rare, it should become less infected than observed in the sexual population (@fig-2-3 B). During this period, there is parasite-mediated selection against sex. Hence, the clone increases in frequency (@fig-2-3 A), only to be driven down again by parasites after it becomes common (@fig-2-3 B). Another cycle begins. **The key point is that parasites do not select against clonal reproduction per se; they only select against common genotypes.** But selection against common host genotypes might be sufficient to prevent fixation of a clone in the short term. </span>
<span id="cb1-71"><a href="#cb1-71"></a></span>
<span id="cb1-72"><a href="#cb1-72"></a><span class="al">![Simulation model showing that coevolving parasites can prevent the fixation of asexuals in the short term. **A.** The number of sexual and asexual individuals over time. **B.** The frequency of infection in sexual and asexual individuals over time. The simulation introduces a single clonal genotype into a sexual population at carrying capacity. After the clone becomes common (**A**) the parasites evolve to "target" it for infection (**B**). Note that after the parasites have driven the clone's frequency down, the asexuals are less infected than the sexuals. Simulation model based on Lively (2009), which treats parasite virulence as a positive function of host density.](images/fig2-3.jpg)</span>{fig-alt="" #fig-2-3}</span>
<span id="cb1-73"><a href="#cb1-73"></a></span>
<span id="cb1-74"><a href="#cb1-74"></a>This scenario of fluctuating selection for and against sex is just a special case of the more general idea that parasites will select against common genotypes within a diverse, sexual host population. As a rare host genotype becomes common, the parasites genotype that can infect it will be favored by natural selection. If the parasite is virulent (meaning that infection reduces host fitness), the targeted host genotype will decline in frequency, and a new host genotype will begin to increase in frequency. Under this logic, host-parasite coevolution will lead to the oscillation of genotypes in both the host and the parasite populations (@fig-2-4). These oscillations are now called Red Queen dynamics. Red Queen dynamics can lead to the maintenance of genetic polymorphism in sexual populations, and possibly protect sexual reproduction from replacement by asexual lineages. In addition, Red Queen dynamics could also favor recombination within a sexual population (Peters and Lively 1999, Schmid-Hempel and Jokela 2002, Peters and Lively 2007, Salathe et al. 2008). These related ideas are now called the Red Queen Hypothesis (following Bell 1982). </span>
<span id="cb1-75"><a href="#cb1-75"></a></span>
<span id="cb1-76"><a href="#cb1-76"></a><span class="al">![Red Queen dynamics. The frequency of a single host genotype is shown along with the frequency of the only parasite genotype that can infect it. Note that the parasite tracks the host with a time lag. Results were extracted from a simulation of a sexual host population with nine possible genotypes coevolving with an asexual parasite with nine matching genotypes Lively (2009). The dashed line shows the average genotype frequency for hosts and parasites.](images/fig2-4.jpeg)</span>{fig-alt="" #fig-2-4}</span>
<span id="cb1-77"><a href="#cb1-77"></a></span>
<span id="cb1-78"><a href="#cb1-78"></a><span class="fu">### An intersection of science and literature</span></span>
<span id="cb1-79"><a href="#cb1-79"></a></span>
<span id="cb1-80"><a href="#cb1-80"></a>The name for the Red Queen Hypothesis comes from *Through the Looking Glass* (Carroll 1872). Here are the relevant bits of the story. After Alice goes through the looking glass (a mirror), she decides to follow a straight path to the top of a hill. But, in following the path, she ends up at her starting point. Talking to herself, she remarks, "But how curiously it twists!  It's more like a corkscrew than a path."  Repeated attempts were unsuccessful. In frustration, Alice addresses a tiger lily amongst a patch of flowers, "I wish you could talk!"  The lily informs Alice that all the flowers can talk. The stunned Alice then begins a conversation with the flowers before finally asking, *Are there more people in the garden besides me?*  The rose answers *yes, there is someone like you.* Alice sets out to follow this person (the Red Queen), but she quickly loses sight of her, and ends up back at her original starting point. Flustered, Alice decides to follow the advice of the rose: "I should advise you to walk the other way."  Alice then quickly finds the Red Queen. </span>
<span id="cb1-81"><a href="#cb1-81"></a></span>
<span id="cb1-82"><a href="#cb1-82"></a>Now it gets especially interesting. Alice mentions to the Red Queen that she would like to "find my way to the top of the hill."  The Red Queen replies: "I could show you hills in comparison with which you'd call that a valley." Alice protests: "a hill ca'n't be a valley... That would be nonsense."  This exchange between Alice and the Red Queen now seems prophetic, because, under frequency-dependent selection, locations on the adaptive landscape can rapidly change from fitness peaks to fitness valleys. Perhaps the Red Queen's statement is correct: hills can become valleys, and valleys can become hills. More specifically, genotypes that were favored by natural selection when rare can become selected against after they become common, leading to a highly dynamic adaptive landscape. </span>
<span id="cb1-83"><a href="#cb1-83"></a></span>
<span id="cb1-84"><a href="#cb1-84"></a>In any case, Alice had clearly entered a crazy world. Straight paths become like corkscrews, progress is made by going the other way, and hills become valleys. Then, suddenly, Alice and the Red Queen began to run: "Alice never could quite make out, in thinking afterwards, how it was that they began: all she remembers is, that they were running hand in hand, and the Queen went so fast that it was all she could do to keep up with her." During this furious run, Alice notices that they never pass anything. The trees remain in the same place as if they were moving along with them. Alice eventually asks: "Are we nearly there?" The Red Queen replies: "Why, we passed it ten minutes ago! Faster!"</span>
<span id="cb1-85"><a href="#cb1-85"></a></span>
<span id="cb1-86"><a href="#cb1-86"></a>When they finally stop, Alice is surprised to be where they started: "I do believe we have been under this tree the whole time! Everything is just as it was!" The Red Queen replies that of course, and then asks: "What would you have it?" Alice replies that she would have expected to get somewhere else after running for a long time. The Red Queen then replies with this very famous quote: "Now, *here*, you see, it takes all the running *you* can do to keep in the same place." It is a perfect metaphor for host-parasite coevolution<span class="ot">[^9]</span>. Host and parasite genotypes might oscillate as if they were running to stay in the same place.</span>
<span id="cb1-87"><a href="#cb1-87"></a></span>
<span id="cb1-88"><a href="#cb1-88"></a>It seems unlikely that Lewis Carroll had coevolution in mind when writing these passages. But he was a mathematician at Oxford University (his given name was Charles Dodgson), and at least one author has shown how his writings can be seen as metaphors for mathematical problems  (Bayley 2009, 2010). Along these lines, mathematician Sanderson M. Smith has suggested that <span class="co">[</span><span class="ot">Carroll simply inverted the equation for speed from "speed = distance/time" to "speed = time/distance"</span><span class="co">](http://www.herkimershideaway.org/writings/carroll.htm)</span>. Upon rearrangement, the latter gives "distance = time/speed." Hence you must run very fast to stay in the same place. But how does the shifting landscape fit in? And why did Alice have to go the other way to meet the Red Queen? I would love to know.</span>
<span id="cb1-89"><a href="#cb1-89"></a></span>
<span id="cb1-90"><a href="#cb1-90"></a>It is perhaps worth pointing out that the phrase "Red Queen Hypothesis" can have two different meanings to evolutionary biologists. In the early 1970s, Leigh van Valen was grappling with data showing that the probability of extinction in very different organisms was independent of the age of the lineage. He reasoned that, in coevolutionary interactions, the probability of one species driving the other species extinct could, in fact, be independent of lineage age (Van Valen 1973). It thus seems reasonable to suggest that both antagonists must run (coevolve) as fast as they can to prevent extinction. Graham Bell repurposed the phrase to mean within-population oscillations in host and parasite genotypes (Bell 1982). Hence, Van Valen's idea is about macroevolution (speciation/extinction), while Bell's idea is about microevolution. Even though van Valen's use of the Red Queen metaphor was published first, I will use Bell's microevolutionary meaning, as it perfectly captures the oscillating nature of genotype frequencies during host-parasite coevolution.<span class="ot">[^10]</span></span>
<span id="cb1-91"><a href="#cb1-91"></a></span>
<span id="cb1-92"><a href="#cb1-92"></a><span class="fu">### Conceptual roots of the Red Queen Hypothesis</span></span>
<span id="cb1-93"><a href="#cb1-93"></a></span>
<span id="cb1-94"><a href="#cb1-94"></a>Part of my goal is to show science as a process. As such it seems reasonable to discuss the origins of the Red Queen idea. One of the earliest statements alluding to the Red Queen Hypothesis came from W.D. Hamilton (1975). Hamilton was reviewing the books by Williams (1975) and Ghiselin (1974) for the *Quarterly Review of Biology*. Throughout the review, the reader can feel Hamilton's frustration with their arguments. Towards the end, he makes this very abstract suggestion: “…it seems to me that we need environmental fluctuations around a trend line of change" and “For the source of these we may look to fluctuations and periodicities … generated by life itself.”</span>
<span id="cb1-95"><a href="#cb1-95"></a></span>
<span id="cb1-96"><a href="#cb1-96"></a>The quote does not specifically refer to parasites, but it does suggest that coevolutionary interactions, in general, could play a role in selecting for sex and recombination. In his memoirs, Hamilton clears this up, writing: "At that stage when I wrote the review, although I had not seen the particular relevance that parasitism might have, I had for many years seen sex looming ahead and had reached a stage of being excited by the possible primary role of biotic interaction. I had decided that it was in aspects of the interspecies struggle, and not survival in an inanimate environment, that I had to search for the main factor. Adaptation to new physical habitats might be made possible through sexuality but these adaptations could not be the main reason for its existence (Hamilton 2001)."</span>
<span id="cb1-97"><a href="#cb1-97"></a></span>
<span id="cb1-98"><a href="#cb1-98"></a>Note that, here, Hamilton is specifically contrasting host-parasite coevolution with the Lottery Model, which relies on random changes in "physical habitats."  </span>
<span id="cb1-99"><a href="#cb1-99"></a></span>
<span id="cb1-100"><a href="#cb1-100"></a>At about the same time, a plant population biologist, Don Levin, was also writing on the paradox of sex/rec. In his paper, Levin specifically identified pathogens as a possible force selecting for recombination (Levin 1975): "I propose that the persistent tracking of plant hosts by multiple pathogens and herbivores is a prime factor which prohibits the congealing of the genomes of species, especially those in closed communities."</span>
<span id="cb1-101"><a href="#cb1-101"></a></span>
<span id="cb1-102"><a href="#cb1-102"></a>Boom! By "prohibit the congealing of genomes," Levin means, "selects for recombination." The reference to "closed communities" means species that are tightly coevolving in the absence of homogenizing gene flow. This quote seems to be the first to specifically identify coevolving pathogens as a primary source of selection favoring the mixing of genomes. Levin's idea was quickly followed by important conceptual contributions by Glesener &amp; Tilman (1978)<span class="ot">[^11]</span>, Jaenike (1978)<span class="ot">[^12]</span>, and Lloyd (1980). In particular, Lloyd writes: “... biological interactions are more likely than unpredictable physical conditions to provide the kind of relentless, repetitive change that is necessary for sexual parents to be selected because of the genetic diversity that sex engenders.”</span>
<span id="cb1-103"><a href="#cb1-103"></a></span>
<span id="cb1-104"><a href="#cb1-104"></a>Lloyd then turns this abstract idea into a specific prediction, which I would later test: “If this proves to be so, we will then be able to examine whether the occurrence of asexual reproduction is correlated with relaxation of the biological hostility of the environment.” Notice that, in the quotes presented above, both Hamilton and Lloyd were specifically predicting that coevolution is more important in selecting for sex than uncertain physical environments. But it is reasonable to ask, does it really matter?  Aren't both ideas fundamentally about bet hedging in uncertain environments? Yes: I think both ideas are about bet hedging. But the distinction still matters. The Lottery Model is about random shifts in the direction of selection; there is no selection against common genotypes unless the environment changes by chance in a way that disfavors them. By contrast, under the Red Queen, selection is frequency dependent. In fact, selection against common genotypes is the core of the model. Hence, the critical difference between the models is not so much about bet hedging but whether selection for sex/rec is directional (but randomly changing directions, a lottery) or frequency dependent (Red Queen). For example, parasites could be a source of directional selection for sex if they randomly changed which host genotypes they attacked. To my mind, that would be a Lottery Model. The Red Queen Hypothesis requires frequency-dependent selection generated by interactions between species.<span class="ot">[^13]</span> This is an important distinction. </span>
<span id="cb1-105"><a href="#cb1-105"></a></span>
<span id="cb1-106"><a href="#cb1-106"></a>Taking this view, the Red Queen Hypothesis may seem more closely related to the Tangled Bank model than to the Lottery Model, as both the Red Queen and the Tangled Bank rely on frequency-dependent selection. But the critical distinction here is that selection against common genotypes under the Tangled Bank relies on intraspecific competition in populations at carrying capacity (soft selection). The Red Queen relies on interspecific antagonistic coevolution, leading to parasite-mediated selection against common host genotypes.<span class="ot">[^14]</span></span>
<span id="cb1-107"><a href="#cb1-107"></a></span>
<span id="cb1-108"><a href="#cb1-108"></a>In any case, looking back, it seems clear that the architects of the ecological hypotheses had two inter-related things in mind: </span>
<span id="cb1-109"><a href="#cb1-109"></a></span>
<span id="cb1-110"><a href="#cb1-110"></a><span class="ss">1. </span>How can we explain sex/rec, and </span>
<span id="cb1-111"><a href="#cb1-111"></a><span class="ss">2. </span>How do we understand the biogeographic and phylogenetic distributions of asexual reproduction?  </span>
<span id="cb1-112"><a href="#cb1-112"></a></span>
<span id="cb1-113"><a href="#cb1-113"></a>As an evolutionary ecologist, I was drawn to the confluence of these questions. But other ideas were also interesting, such as the idea that sexual reproduction is favored because it reduces the interference between alleles at different loci (review in Otto 2021). I will cover some special cases of this latter idea in @sec-chap6.<span class="ot">[^15]</span> </span>
<span id="cb1-114"><a href="#cb1-114"></a></span>
<span id="cb1-115"><a href="#cb1-115"></a><span class="fu">## Summary</span></span>
<span id="cb1-116"><a href="#cb1-116"></a></span>
<span id="cb1-117"><a href="#cb1-117"></a><span class="ss">1. </span>Three ecological hypotheses have been proposed to explain the persistence of cross-fertilization in the face of competition with uniparental reproductive strategies such as parthenogenesis or self-fertilization (following Bell 1982). </span>
<span id="cb1-118"><a href="#cb1-118"></a></span>
<span id="cb1-119"><a href="#cb1-119"></a><span class="ss">2. </span>The Lottery Model is based on the possible advantages of diversifying offspring facing uncertain changes in the abiotic environment. Here selection is independent of both density and frequency. </span>
<span id="cb1-120"><a href="#cb1-120"></a></span>
<span id="cb1-121"><a href="#cb1-121"></a><span class="ss">3. </span>The Tangled Bank and Frozen Niche-Variation Hypotheses are based on competition for resources when multiple resource types co-occur. Selection is frequency dependent, but the advantage to rare types only occurs when intraspecific competition is intense. </span>
<span id="cb1-122"><a href="#cb1-122"></a></span>
<span id="cb1-123"><a href="#cb1-123"></a><span class="ss">4. </span>The Red Queen Hypothesis relies on parasite-mediated selection against common host genotypes. Such selection, when strong, can result in oscillatory changes in parasite and host alleles. These oscillations are sometimes called Red Queen dynamics. </span>
<span id="cb1-124"><a href="#cb1-124"></a></span>
<span id="cb1-125"><a href="#cb1-125"></a><span class="ss">5. </span>A bet-hedging strategy reduces the variance in reproductive success over time, even if it reduces the arithmetic mean. Sexual reproduction under the Lottery Model is clearly a bet-hedging strategy. The Red Queen idea can perhaps also be seen as bet hedging.  </span>
<span id="cb1-126"><a href="#cb1-126"></a></span>
<span id="cb1-127"><a href="#cb1-127"></a>::: {.callout-note #callout-3}</span>
<span id="cb1-128"><a href="#cb1-128"></a><span class="fu">## Box 2.1. Levene's model of multiple niche polymorphism. {#callout-3}</span></span>
<span id="cb1-129"><a href="#cb1-129"></a></span>
<span id="cb1-130"><a href="#cb1-130"></a>It was widely thought that heterozygote advantage was required to maintain polymorphism at a single locus with two alleles. In the introduction to his paper, Levene wonders "...whether it was in fact possible to have an equilibrium without the heterozygote being superior in any single niche." The paper is not easy to follow, even though the algebra is not difficult. Here I try to simplify the presentation. </span>
<span id="cb1-131"><a href="#cb1-131"></a></span>
<span id="cb1-132"><a href="#cb1-132"></a>Levene first assumes that the proportion of survivors coming from the $i^{th}$ niche is constant $(q)$, independent of the genotypic composition of the niche (i.e., soft selection). He then assumes that the heterozygote has a relative fitness of 1 in all niches, giving $W_{AB} = 1$. Let $q$ be the frequency of allele A, and let ($1 - q$) be the frequency of allele B. The frequency of allele A in the next generation, $q'$, is then</span>
<span id="cb1-133"><a href="#cb1-133"></a></span>
<span id="cb1-134"><a href="#cb1-134"></a>$$q^{'} = \sum_{}^{}c_{i}\frac{q^{2}W_{AAi} + q(1 - q)}{q^{2}W_{AAi} + 2q(1 - q) + (1 - q)^{2}W_{BBi}}$$</span>
<span id="cb1-135"><a href="#cb1-135"></a></span>
<span id="cb1-136"><a href="#cb1-136"></a>The change in $q$ is simply $\mathrm{\Delta}q = q^{'} - q$. Under these assumptions, Levene showed that A allele will increase when rare (barring genetic drift) when                                     |</span>
<span id="cb1-137"><a href="#cb1-137"></a></span>
<span id="cb1-138"><a href="#cb1-138"></a>$$\frac{1}{\sum_{}^{}{c_{i}\frac{1}{W_{AAi}}}} &lt; 1$$</span>
<span id="cb1-139"><a href="#cb1-139"></a></span>
<span id="cb1-140"><a href="#cb1-140"></a>where the left-hand side gives the harmonic mean fitness for genotype AA over all niches. The right-hand-side of the equation gives the harmonic mean fitness of the heterozygous genotype, AB, which is equal to 1. Similarly, the B allele will increase when rare when </span>
<span id="cb1-141"><a href="#cb1-141"></a></span>
<span id="cb1-142"><a href="#cb1-142"></a>$$\frac{1}{\sum_{}^{}{c_{i}\frac{1}{W_{BBi}}}} &lt; 1$$</span>
<span id="cb1-143"><a href="#cb1-143"></a></span>
<span id="cb1-144"><a href="#cb1-144"></a>where the left-hand side gives the harmonic mean fitness for genotype BB over all niches. A genetic polymorphism is expected if both alleles can increase when rare, hence **polymorphism is expected when, in general, when the harmonic mean fitness for the heterozygote is greater than the harmonic mean fitness for either homozygote**.  </span>
<span id="cb1-145"><a href="#cb1-145"></a></span>
<span id="cb1-146"><a href="#cb1-146"></a>But does this require that the AB genotype is the most fit in at least one niche? Levene gives a specific example to answer this question. He assumes two niches, where the proportion of survivors from both niches is equal (i.e., $c_{1} = c_{2} = 0.5$). He then assumes genotypic fitness values, as given in the following table. It is important to note that the heterozygous genotype is not the most fit genotype in either niche.                                         </span>
<span id="cb1-147"><a href="#cb1-147"></a></span>
<span id="cb1-148"><a href="#cb1-148"></a></span>
<span id="cb1-149"><a href="#cb1-149"></a>| Genotype | **Fitness Niche 1** | **Fitness Niche 2** | **Arithmetic mean** |  **Harmonic mean** |</span>
<span id="cb1-150"><a href="#cb1-150"></a>| ---------| --------------------|---------------------|-----------| -------------- |</span>
<span id="cb1-151"><a href="#cb1-151"></a>| **AA** | $W_{AA1}$ = 1.50 | $W_{AA2}$ = 0.67 | 1.09 | 0.93 |</span>
<span id="cb1-152"><a href="#cb1-152"></a>| **AB** | $W_{AB1}$ = 1.00 | $W_{AB2}$ = 1.00 |  1.00 | 1.00 |</span>
<span id="cb1-153"><a href="#cb1-153"></a>| **BB** | $W_{BB1}$ = 0.67 | $W_{BB2}$ = 1.50 | 1.09 | 0.93 |</span>
<span id="cb1-154"><a href="#cb1-154"></a></span>
<span id="cb1-155"><a href="#cb1-155"></a>For this example, the harmonic mean fitness for the heterozygote is greater than the harmonic mean fitness for either homozygote, thus meeting the conditions given by the equations above. Thus, the answer to Levene's question is yes. It is possible to have a genetic polymorphism without having heterozygote advantage in any single niche. And, interestingly, the polymorphism is expected even though the arithmetic mean fitness of the heterozygote is less than the arithmetic mean fitness of either homozygote. Finally, based on this example, it seems that a trade-off is required, such that the AA genotype does best in one niche, and the BB genotype does best in the other niche. </span>
<span id="cb1-156"><a href="#cb1-156"></a></span>
<span id="cb1-157"><a href="#cb1-157"></a>Nonetheless, Levene's result suggests that overdominance for harmonic mean fitness is required for multiple niche polymorphism (Prout 1968). However, Timothy Prout showed that a polymorphism could be stable, even if one allele is dominate, thus ruling out any kind of overdominance (Prout 1968). Let both the AA and AB genotypes have a fitness of 1 in both niches. Let the BB genotype have a fitness of 0.5 in niche 1 and a fitness of 1.67 in niche 2. Assuming as above that both patches are equally common, we get the following table.</span>
<span id="cb1-158"><a href="#cb1-158"></a></span>
<span id="cb1-159"><a href="#cb1-159"></a>| Genotype | **Fitness Niche 1** | **Fitness Niche 2** | **Arithmetic mean** |  **Harmonic mean** |</span>
<span id="cb1-160"><a href="#cb1-160"></a>| ---------| --------------------|---------------------|-----------| -------------- |</span>
<span id="cb1-161"><a href="#cb1-161"></a>| **AA** | $W_{AA1}$ = 1.00 | $W_{AA2}$ = 1.00 | 1.00 | 1.00 |</span>
<span id="cb1-162"><a href="#cb1-162"></a>| **AB** | $W_{AB1}$ = 1.00 | $W_{AB2}$ = 1.00 |  1.00 | 1.00 |</span>
<span id="cb1-163"><a href="#cb1-163"></a>| **BB** | $W_{BB1}$ = 0.50 | $W_{BB2}$ = 1.67 | 1.09 | 0.77 |</span>
<span id="cb1-164"><a href="#cb1-164"></a></span>
<span id="cb1-165"><a href="#cb1-165"></a>Prout showed that there would be a stable multiple niche polymorphism, even under complete dominance, provided that the arithmetic mean fitness for BB is greater than 1, and that the harmonic mean fitness for the BB genotype is less than 1. So, clearly, overdominance for harmonic mean fitness is not required for a stable polymorphism.<span class="ot">[^16]</span>  </span>
<span id="cb1-166"><a href="#cb1-166"></a></span>
<span id="cb1-167"><a href="#cb1-167"></a>The plot below shows $\mathrm{\Delta}q$ as a function of $q$ for Prout's model of dominance. Note that $\mathrm{\Delta}q$ is positive when $q$ is near zero, and that $\mathrm{\Delta}q$ is negative when $q$ is near 1. There is an interior equilibrium near $q = 0.5$.</span>
<span id="cb1-168"><a href="#cb1-168"></a></span>
<span id="cb1-169"><a href="#cb1-169"></a><span class="al">![](images/fig2-5.jpg)</span>{fig-alt="" width=65% fig-align="center"} </span>
<span id="cb1-170"><a href="#cb1-170"></a></span>
<span id="cb1-171"><a href="#cb1-171"></a><span class="co">&lt;!--The papers by Levene (1953) and Prout (1968) helped to lay the foundation for the fusion of population genetics and population ecology.--&gt;</span></span>
<span id="cb1-172"><a href="#cb1-172"></a>:::</span>
<span id="cb1-173"><a href="#cb1-173"></a></span>
<span id="cb1-174"><a href="#cb1-174"></a></span>
<span id="cb1-175"><a href="#cb1-175"></a><span class="ot">[^1]: </span>See Bell (1982) for a deeper historical view of the Lottery Model, which involves contributions by Maynard Smith and others, including Williams. I have tried to distill it down to a simple bet-hedging model here. The original formulation is more complex. </span>
<span id="cb1-176"><a href="#cb1-176"></a></span>
<span id="cb1-177"><a href="#cb1-177"></a><span class="ot">[^2]: </span>The variance in $x$ is equal to the average of the squared deviations from the mean: $var(x) = \frac{1}{N}\sum_{i = 1}^{N}{(x_{i} - \overline{x})^{2}}$</span>
<span id="cb1-178"><a href="#cb1-178"></a></span>
<span id="cb1-179"><a href="#cb1-179"></a><span class="ot">[^3]: </span>The geometric mean is the $N^{th}$ root of the product of $N$ observations. Compared to the arithmetic mean, the geometric mean gives more weight to small values.</span>
<span id="cb1-180"><a href="#cb1-180"></a></span>
<span id="cb1-181"><a href="#cb1-181"></a><span class="ot">[^4]: </span>The bet-hedging idea dates to Daniel Bernoulli, a mathematical physicist, writing in 1738. Steve Stearns (2000) provides an important, fascinating review of how evolutionary biologists (beginning with Cohen (1966)) and economists, have borrowed from Bernoulli's conceptual framework. </span>
<span id="cb1-182"><a href="#cb1-182"></a></span>
<span id="cb1-183"><a href="#cb1-183"></a><span class="ot">[^5]: </span>Vrijenhoek studied the coexistence of sexual fish with multiple clonal genotypes of asexual congeners in natural populations. He mainly envisioned the Frozen Niche Hypothesis as a model to explain the coexistence of multiple clones, but it can also explain the coexistence of sexual and asexual modes of reproduction if clonal diversity is low, and the clones do not compete strongly. See, for example pages 112-113 in Vrijenhoek and Parker (2009): "The Frozen Niche-Variation Model (Vrijenhoek 1978, 1979) was directly stimulated by Roughgarden's (1972) ideas and a need to explain the stable coexistence of* Poeciliopsis *fish clones in spatially heterogeneous desert streams (Vrijenhoek 1978)."</span>
<span id="cb1-184"><a href="#cb1-184"></a></span>
<span id="cb1-185"><a href="#cb1-185"></a><span class="ot">[^6]: </span>Soft selection in theoretical population genetics can also mean that the contribution of offspring from different demes in a metapopulation is unrelated to differences in mean fitness among demes.</span>
<span id="cb1-186"><a href="#cb1-186"></a></span>
<span id="cb1-187"><a href="#cb1-187"></a><span class="ot">[^7]: </span>Wallace (1975) explains that the source of the terms "soft" and "hard" stem from financial discussions of soft currencies vs hard currencies in monetary exchanges. Soft currencies only have value within their home country. In contrast, hard currencies can be exchanged overseas for currencies with similar buying power.</span>
<span id="cb1-188"><a href="#cb1-188"></a></span>
<span id="cb1-189"><a href="#cb1-189"></a><span class="ot">[^8]: </span>I use "parasite" here in the ecological sense to include any organism that lives in, or on, its host, provided it reduces the survivorship and/or fecundity of its host. As such, the term includes both macroparasites (such as worms) and microparasites (such as protozoans, bacteria, and viruses).</span>
<span id="cb1-190"><a href="#cb1-190"></a></span>
<span id="cb1-191"><a href="#cb1-191"></a><span class="ot">[^9]: </span>The intersection between science and literature is not restricted to selection for or against sex. For a fascinating essay on how the biology of parasites meets literature, see Justyna Jajszczok's dissertation (Jajszczok 2017).</span>
<span id="cb1-192"><a href="#cb1-192"></a></span>
<span id="cb1-193"><a href="#cb1-193"></a><span class="ot">[^10]: </span>I. M. Lerner used the Red Queen metaphor as early as 1954, with respect to the selection needed to maintain genetic homeostasis: "The *Alice in Wonderland* situation in which 'it takes all the running you can do to stay in the same place' arises when a stationary level of performance can be maintained only by application of the maximum selection possible..." (See page 117 in Lerner (1954)). </span>
<span id="cb1-194"><a href="#cb1-194"></a></span>
<span id="cb1-195"><a href="#cb1-195"></a><span class="ot">[^11]: </span>For example, Glesener and Tilman write: "Thus, sexuality not only is favored under changed conditions but is, itself, capable of changing the conditions. The sexuality of an organism's competitors, predators, parasites, etc., will greatly increase the selective pressure for sexuality on that organism as well."</span>
<span id="cb1-196"><a href="#cb1-196"></a></span>
<span id="cb1-197"><a href="#cb1-197"></a><span class="ot">[^12]: </span>Jaenike focuses more on the recycling of genotypes: "My hypothesis differs from Levin's in that sex and recombination are advantageous not to produce novel genotypes as such, but to produce rare genotypes, of which novel ones are only a subset.”</span>
<span id="cb1-198"><a href="#cb1-198"></a></span>
<span id="cb1-199"><a href="#cb1-199"></a><span class="ot">[^13]: </span>I use “frequency-dependent” selection here to mean selection against common genotypes. A more accurate phrase would be “negative frequency-dependent” selection. </span>
<span id="cb1-200"><a href="#cb1-200"></a></span>
<span id="cb1-201"><a href="#cb1-201"></a><span class="ot">[^14]: </span>This is not meant to imply, however, that the strength of parasite-mediated selection under the Red Queen Hypothesis must be independent of population size. Indeed, as we will see, there are good reasons to think that the strength of parasite-mediated selection depends on host density.</span>
<span id="cb1-202"><a href="#cb1-202"></a></span>
<span id="cb1-203"><a href="#cb1-203"></a><span class="ot">[^15]: </span>The basic idea comes from a paper by Hill and Robertson (1966), and is often called the Hill-Robertson effect (following Felsenstein 1974). A broader framework, housed under the more intuitive phrase “selective interference,” was recently given by Sarah Otto as part of a keynote lecture given to the American Genetic Association (Otto 2021).</span>
<span id="cb1-204"><a href="#cb1-204"></a></span>
<span id="cb1-205"><a href="#cb1-205"></a><span class="ot">[^16]: </span>The harmonic mean is not intuitive to most Biology students. So, I ask them this question: if you had a score of 100 on your first exam, and a score of 60 on your second exam, would you rather have your final grade calculated as the arithmetic mean or the harmonic mean of the two scores? After some thought, they all pick the arithmetic mean. That is because the harmonic mean weights low scores more heavily than high scores.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>